### ISSUE TITLE
Create Collection form does not save the first, preselected entry of the Entity Type dropdown

### ISSUE THREAD

**Issue by MW3000** [DSpace/dspace-angular#2123] opened 2023-02-27 10:12 UTC
**Describe the bug**
Create Collection form does not save the first, preselected entry of the Entity Type dropdown. This results in the Collection not being associated with an entity type. Which in turn results in this bug: https://github.com/DSpace/dspace-angular/issues/1661

**To Reproduce**
1. Enable entities. Use the default configuration.
2. Create a new collection
3. Do not touch the entity type dropdown. You want to have the "preselected" first entry.
4. Save the new collection
5. Check the database, if your new collection has a metadata entry for entity type. It does not.

**Expected behavior**
The preselected first entry should be written to the database when clicking save.

**Related work**
This explains https://github.com/DSpace/dspace-angular/issues/1661

<img width="846" alt="Screenshot 2023-02-27 at 11 11 12" src="https://user-images.githubusercontent.com/8408850/221535542-3869a2c9-fb63-47cc-989b-a439b090d08f.png">

**Comment by tdonohue** [comment] 2023-02-27 17:29
@MW3000 : What version of DSpace is this in?  And what web browser are you using?

On DSpace 7.5 in Chrome, I'm *not* seeing this pre-selected Entity Type when I go to "New -> Collection" (and select a parent Community).  Instead, I see this:
![new-collection](https://user-images.githubusercontent.com/483997/221637611-b7180e4b-16e4-4987-b5fd-86c970e56e95.png)

By default, this Entity Type fields **should be empty**, which means the Collection just uses normal Items.  So, it's odd to me that it's set to "Publication" by default for you.

**Comment by MW3000** [comment] 2023-02-27 20:38
I use DSpace 7.5 with Safari Version 16.3 on macOS Ventura 13.2.

I just tested again. It happens reproducible with Safari, but does not happen with Firefox.

**Comment by tdonohue** [comment] 2023-02-27 20:50
@MW3000 : Thanks for further testing. It sounds more like our dropdown code/component/library isn't working properly in Safari.  Maybe Safari is somehow picking up the first value as the "default" even when we want to the default to be no value.  Not sure why that would be offhand, but it sounds like a bug specific to how Safari is displaying dropdowns.

Perhaps we should close this ticket (as it's not the core problem) and reopen one about dropdown display in Safari?  If you've seen similar behavior in other dropdowns, could you provide screenshots or notes on the other dropdowns affected?  That may help us narrow down the root cause, as obviously we should ensure Safari works the same as other browsers.

**Comment by MW3000** [comment] 2023-02-28 15:25
@tdonohue I described the issue with Safari dropdowns in https://github.com/DSpace/dspace-angular/issues/2124

Still a better error message that mentions the actual entity types of the items in question would lead to more clarity on the issue in https://github.com/DSpace/dspace-angular/issues/1661

**Comment by tdonohue** [comment] 2023-02-28 18:21
Thanks @MW3000 ! I'm going to close this ticket , as I think it's replaced by #2124.  Will pull that other ticket over to our 7.6 board and see if I can find a volunteer to fix it.  Hoping it's something small.

**Closed by tdonohue** 2023-02-28 18:21 UTC
Labels: bug, needs triage
