### ISSUE TITLE
Creative Commons Licence image does not appear on item page.

### ISSUE THREAD

**Issue by priscilla-carmini** [DSpace/dspace-angular#3002] opened 2023-07-26 17:19 UTC
The Creative Commons licence image and link do not appear in item records in version 7.6. They do appear in version 6.4 (See image below). CC licence information appears in our metadata in 7.6, but not in the item record. 

<img width="565" alt="image" src="https://github.com/DSpace/DSpace/assets/57642282/4a65081b-a85e-41e4-a7cb-d3fa3ffff363">

We would like the CC licence image to display on the item page. We would also like the image to link to the licence deed on the Creative Commons website.

**Comment by tdonohue** [comment] 2024-05-03 14:12
@autavares-dev : This issue has now been transferred to `dspace-angular`.  Technically, you are welcome to create a PR and link to the issue wherever the issue ticket exists, but I moved it to `dspace-angular` just to make it easier to locate :)   Please feel free to create a PR if you have time/interest.

**Comment by autavares-dev** [comment] 2024-05-03 16:53
@tdonohue I have code/PR ready for version 8.x.
But I see the issue is related to the [DSpace 7.6.x Maintenance](https://github.com/orgs/DSpace/projects/29) project.
Can I do the PR for the 8.x branch or is it preferred to use the 7.x branch?

**Comment by tdonohue** [comment] 2024-05-03 17:36
@autavares-dev : You can create a PR for either version. It doesn't matter to us.  For small PRs, we have an automatic process which will create a copy of the PR for the other branch (and usually it works well).  If the automatic process doesn't work, we will do our best to port it to the other branch.

**Closed** 2024-05-09 21:42 UTC
Labels: bug, low priority, integration: Creative Commons

**Comment by Peredwel** [comment] 2026-04-21 15:29
Question:  Does this feature work if the institution is using the oaire_license_types for their Creative Commons licenses?  Nota bene: If the institution uses the OpenAire dropdown menu to select their license, it saves the license in a different field, oaire_license_condition, than it does if you select your license via the API (dc.rights.uri & dc.rights).  Not sure what the implications will be longterm for having consistent metadata.
