### ISSUE TITLE
Search sort options are hardcoded

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#549] opened 2019-12-20 09:09 UTC
Currently the sort options in search [are hardcoded](https://github.com/DSpace/dspace-angular/blob/31c96946669ede1a3dbbdcaba2f83f00c7e9c0ae/src/app/%2Bsearch-page/search-settings/search-settings.component.ts#L34). They should be retrieved from the [`/discover/search` endpoint](https://github.com/DSpace/Rest7Contract/blob/master/search-endpoint.md#search-endpoint). 

Note that you need to pass the configuration to that endpoint to retrieve them as the sort options can change based on it.

**Comment by tdonohue** [comment] 2019-12-20 19:25
NOTE: this hardcoding causes the sort options to **not work** for all search configurations.  One example is in the Relationships modal (in Submission form) as described in bullet 6 in [this PR comment](https://github.com/DSpace/dspace-angular/pull/531#pullrequestreview-334742967).

**Comment by artlowel** [comment] 2021-02-19 13:14
@tdonohue I came across this again today, we should assign this issue to a milestone

**Comment by tdonohue** [comment] 2021-02-19 15:03
@artlowel : Do you have a rough estimate of what this would take?  If you feel it's small (<=4 hrs) we may be able to squeeze this into Beta 5.  But, if it's larger than that, I feel it may need to wait for post-Testathon...and we can try to get it done between Beta 5 and 7.0 Final.

**Comment by artlowel** [comment] 2021-03-04 10:51
Because the discovery endpoints don't all have distinct types and self links, they can't be parsed by the default response parser, so this isn't a trivial fix. We need to:
- extend the FacetConfigResponseParsingService to also parse sortOptions
- also return these sortOptions in searchService.getConfig
- Call searchService.getConfig and use in SearchSettingsComponent, similar to the way it happens in SearchFiltersComponent
- Add/fix tests.

This will take an estimated **6h**

**Comment by tdonohue** [comment] 2021-04-16 16:56
This appears to be a duplicate of #1071, and is therefore being fixed by #1086.  Closing this issue ticket as work is already in progress to fix the issue.

**Closed by tdonohue** 2021-04-16 16:56 UTC
Labels: bug, component: Discovery, e/6
