### ISSUE TITLE
Can't insert different identifiers in the submission form

### ISSUE THREAD

**Issue by alemarte** [DSpace/dspace-angular#950] opened 2020-11-19 11:46 UTC
**Describe the bug**
Inserting different identifiers in a submission doesn't work. The Patch operation is malformed and the submission can't be saved without a full reload of the page.

**To Reproduce**
1. Login as admin
2. Start a submission in collection Books
3. Insert an identifier of type ISSN and click +
4. Insert an identifier of type Other and click +
5. Save
![caso3error1](https://user-images.githubusercontent.com/63857/99661711-861bd800-2a64-11eb-9ecd-83af6987c0df.png)

The patch operation 
![caso3error2](https://user-images.githubusercontent.com/63857/99661726-8c11b900-2a64-11eb-8f49-7490028aab86.png)

In addition, the submission form results compromised and can be saved again only by refreshing the page.

**Expected behavior**
I would expect no errors and both values saved.

**Comment by alemarte** [comment] 2020-11-19 12:10
Related to this user flow we can find another strange behaviour if at point 4 we delete the Other record before saving.

![caso3bis](https://user-images.githubusercontent.com/63857/99664172-17d91480-2a68-11eb-91cf-2fa8bf430666.png)
As we can see there is also a remove operation containing a /-1 index which is not compliant with the json patch RFC.

**Comment by tdonohue** [comment] 2020-11-20 16:05
I've tentatively pulled this into the Beta 5 board (along with related issues #948 and #949) just for discussion purposes. Once discussed, we may still decide whether to include in Beta 5 or not.

**Comment by tdonohue** [comment] 2021-01-21 19:53
As discussed in today's meeting, we expect this bug will be fixed by the (in progress) fix for #971. Therefore, I'm adding a **0hr** estimate to this bug. If we later find it is not fixed, then we can reanalyze at that time.

**Comment by tdonohue** [comment] 2021-02-23 20:25
I've verified this is NOT fixed by #971, the problem still exists.  This *might* be semi-related to #1032 , as that also seems to be caused by an invalid PATCH request.  @atarix83 : Could you look into this and analyze what might be going on?

**Comment by tdonohue** [comment] 2021-03-04 15:14
Talked today and this should be part of #1025

**Comment by alemarte** [comment] 2021-03-04 17:29
@tdonohue Tested against the latest of https://github.com/DSpace/dspace-angular/pull/1025 and all seem to work good.

**Comment by tdonohue** [comment] 2021-03-05 19:05
After retesting, I've verified this is now *fixed* in #1025.  I'll link this ticket up to that PR.  Thanks @alemarte

**Closed** 2021-04-01 18:53 UTC
Labels: bug, component: submission, e/0
