### ISSUE TITLE
Focus shift issue with Date of issue field in the submission form

### ISSUE THREAD

**Issue by DSquareTechnologies** [DSpace/dspace-angular#1143] opened 2021-05-01 08:08 UTC
**Describe the bug**
Tab sequence does not behave as expected across three subfields appearing under Date of Issue. Upon pressing the tab after entering the year, the focus shifts to Publisher field instead of shifting to month field. However, after entering the year if 'enter' key is pressed then the month gets active, and upon pressing the tab key focus shifts to the month field.

**To Reproduce**
1. Go to the item submission form
2. Enter the year in Year field under the Date of Issue field and click on the tab. The focus will shift to the Publisher field instead of the month.
3. Enter the year in Year field under the Date of Issue field and click enter. You will notice the month field getting active, press tab for shifting focus to the month field.

**Expected behavior**
The focus should shift from Year field to the month field once the user clicks the tab after entering YYYY value in the year field.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment] 2021-05-03 18:38
I can reproduce this both locally & on the demo site. 

It seems to be caused by the month & date fields being disabled until the year (or month) is filled out & deselected. @atarix83 : Assigning this to you & your team for analysis, as this was also reported as part of our accessibility analysis.  Flagging as `medium priority` as it'd be ideal to move between fields by pressing tab.

**Comment by tdonohue** [comment] 2021-07-28 17:47
This appears to be fixed (likely by #1252 which fixes similar issues), although it's worth noting the up/down arrows are now part of the focus when clicking tab (for keyboard accessibility purposes).  So you have to tab past them to get to the month field, but it does work.

**Closed by tdonohue** 2021-07-28 17:47 UTC
Labels: Estimate TBD, accessibility, bug, component: submission, medium priority, testathon
