### ISSUE TITLE
DSpace 8 Search for Existing Communites not working 100%

### ISSUE THREAD

**Issue by K-wachira** [DSpace/dspace-angular#2921] opened 2024-04-11 15:00 UTC
Browsers: Firefox, Edge, Chrome

DSpace 8.0 Sandbox https://sandbox.dspace.org/

Tested as dspacedemo admin. 

I created a community `(Community Creation Test April 11th)`  as dspacedemo admin successfully. 
When I try search for the community, sometimes the results show up, sometimes the results don't. [See Screenshot](https://github.com/DSpace/dspace-angular/assets/55190616/0b643c36-133a-4853-bd53-6e5b6471ddcd) 

**To Reproduce**
1. Login as Dspace demo Admin
2. Click on + New to add new community/collection
3. On the pop-up modal, search for a community
4. Enter value `Community Creation Test April 11th` 
5. Results for search for previous step might show or not, if they do, delete the last character, 
6. Repeat Step 5 and the results at one point will not show. 

**Expected behavior**
Show a list of communities that match the searched string.

**Comment by tdonohue** [comment] 2024-05-02 17:11
This is a duplicate of https://github.com/DSpace/DSpace/issues/8251, which is a known issue also in 7.x.  While I agree it should be fixed, I'm closing this ticket in favor of https://github.com/DSpace/DSpace/issues/8251 as it provides more details about the issue.

**Closed by tdonohue** 2024-05-02 17:11 UTC
Labels: bug, help wanted, low priority, testathon
