### ISSUE TITLE
The "Register DOI" button on the Item status page is not displayed

### ISSUE THREAD

**Issue by aroman-arvo** [DSpace/dspace-angular#3057] opened 2024-05-16 09:44 UTC
**Describe the bug**
The "Register DOI" button on the Item status page is not displayed when 'identifiers.item-status.register-doi' is turned on.
This happens at 7.6.1 (7.6.0 works fine)

**To Reproduce**
1. Set true the property identifiers.item-status.register-doi at config/modules/identifiers.cfg
2. Redeploy when neccesary and restart tomcat
3. Login as admin
4. select an item -> edit -> status
5. (button is not shown)

**Expected behavior**
Button "register DOI" must be shown

**Related work**

**Comment by tdonohue** [comment] 2024-06-05 19:56
Closing, as this was already fixed on 7.x and main.  See #2766 (fixed on main) and #2802 (ported on 7.x)

This ticket is a duplicate of #2765

**Closed by tdonohue** 2024-06-05 19:56 UTC
Labels: bug, needs triage
