### ISSUE TITLE
Hint not visible in the UI for fields with input-type qualdrop_value

### ISSUE THREAD

**Issue by f-rapp** [DSpace/dspace-angular#1321] opened 2021-09-22 09:08 UTC
**DSpace 7**
The hint for a field with input-type qualdrop_value is not visibile in the UI, even though there is a hint for that field in submission-forms.xml.

**To Reproduce**
1. Log into DSpace 7 Demo and start a new submission. Look for a field which has input-type qualdrop_value, e.g. the field below.
![grafik](https://user-images.githubusercontent.com/67266996/134314905-d3907343-a961-4e2f-87a6-845da0ed2e29.png)
2. Check the code in the DSpace 7 GitHub repository. Although there is a hint for that field, the hint is not displayed in the UI.
https://github.com/DSpace/DSpace/blob/main/dspace/config/submission-forms.xml#L150

**Expected behavior**
The hint should be displayed in the UI.

**Comment by yingjin** [comment] 2022-10-31 20:47
I am wondering if this bug is reported for much older DSpace 7 release. I checked my DSpace 7.4 installation, it seems like the problem is not there anymore.

<img width="1332" alt="Screen Shot 2022-10-31 at 3 42 12 PM" src="https://user-images.githubusercontent.com/1444734/199106953-835cdb19-ef34-48c2-a4b1-d423a6498d33.png">

Also, the demo7.dspace.org displays the hints as well.

**Comment by tdonohue** [comment] 2022-10-31 21:00
Thanks @yingjin for the testing.  You are correct, it looks like this was fixed somewhere along the way and the ticket never was closed.  Closing now as fixed.

**Closed by tdonohue** 2022-10-31 21:00 UTC
Labels: bug, help wanted, component: submission, good first issue, medium priority, Estimate TBD
