### ISSUE TITLE
"Type" list keeps growing on DSpace 7

### ISSUE THREAD

**Issue by Aziris** [DSpace/dspace-angular#668] opened 2020-05-13 15:07 UTC
1. Log in to be able to create new item
2. Go to create new Item page and observe the "type" dropdown
3. Once you open it and scroll down, new items get added endlesly

**Comment by tdonohue** [comment] 2020-05-13 15:20
@Aziris : Thanks for reporting this!  It's a known issue that we've scheduled to be fixed in the next beta (beta3) See #482, which is this same issue worded in a different way.

So, this is a duplicate of #482.  I'll close this bug ticket & copy your details over to that ticket.

**Closed by tdonohue** 2020-05-13 15:20 UTC
