### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by muhep06** [DSpace/dspace-angular#1569] opened 2022-03-21 12:59 UTC
Sometimes when I create a new item or just change the page I get stuck on the loading screen. I don't see any error output in developer console or logs. So I don't know exactly what the problem is. But there is such an error and it affects the usage.
![image](https://user-images.githubusercontent.com/6313999/159265028-cbf50543-bae0-45e1-a61c-b48ea44b99c0.png)

Here it is stuck on the loading screen due to the 401 error. There should have been a warning or error screen here.
![image](https://user-images.githubusercontent.com/6313999/159265243-c87a604d-29aa-4f1a-92d9-fa418b78f2b7.png)

Thanks.

**Comment by tdonohue** [comment] 2022-03-21 13:56
@muhep06 : I'd recommend moving this over to one of our Support options documented at https://wiki.lyrasis.org/display/DSPACE/Support   This doesn't sound like a bug, as it sounds like something is erroring out on the backend, or there is a configuration issue between the frontend & backend -- that last screenshot shows the backend is throwing a 401 exception, which is saying you are not authenticated with the backend.

You may want to verify that other actions are working properly after login.  You also should check to see if it's a single Collection that is impacted, or a single logged in user that is impacted.  

I suspect this may be a configuration issue. As, that's generally what causes the user interface to load indefinitely...as usually there was a unexpected response from the REST API, usually caused by a configuration issue. https://wiki.lyrasis.org/display/DSDOC7x/Installing+DSpace#InstallingDSpace-UserInterfacestartstoloadbutthenspins(neverfullyloads)

Closing this as it doesn't sound like a bug in DSpace.  However, we'd gladly help debug it on mailing lists or similar.  If we find there's a bug, we can always reopen.

**Closed by tdonohue** 2022-03-21 13:56 UTC
Labels: bug, needs triage
