### ISSUE TITLE
Bitstream/Attachment appearance issue during submission process

### ISSUE THREAD

**Issue by DSquareTechnologies** [DSpace/dspace-angular#1144] opened 2021-05-01 08:29 UTC
**Describe the bug**
Bitstream/Attachment uploaded at the beginning of the submission process disappears as soon as the "terms acceptance" check box is checked and the "Deposit" button gets deactivated. 

Upon re-uploading the attachment in the same submission process, both fresh and previous attachments uploaded appear. Upon selecting the "terms acceptance" check box on the second attempt, the "Deposit" button remains activated.

**To Reproduce**
1. Go to the item submission form, upload bitstream at the beginning of the process, or drag and drop at any time.
2. Click on the checkbox appearing next to "I confirm the license above". After refresh, you will notice the Deposit button will get de-activated and bitstream uploaded will not appear in the Upload files section.
3. Upload the same bitstream again using any of the available methods
4. Click on the checkbox appearing next to "I confirm the license above". After refresh, you will notice that bitstream will appear twice and the Deposit button will stay active for completing the submission.

**Expected behavior**
Upon clicking the checkbox appearing next to "I confirm the license above", the bitstream added in the form should not disappear and the Deposit button should get activated for finishing submission.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment] 2021-05-03 18:30
I'm able to reproduce this on the demo site (demo7.dspace.org), but I cannot reproduce this locally (in a local.  I think though that it *might* be related to the other bitstream upload issues, namely #1121 .

@atarix83 : Assigning this to you for review/analysis, as I think this is the same issue as #1121, or at least caused by the same process. I've had difficulty reproducing it on my local instance, but it does appear on the demo site.

**Comment by atarix83** [comment] 2021-05-20 13:49
the issue is due to #1121 and it's been resolved within https://github.com/DSpace/dspace-angular/pull/1201

**Closed** 2021-06-25 19:44 UTC
Labels: bug, component: submission, duplicate, e/0, high priority
