### ISSUE TITLE
Clicking "Import -> [ANY OPTION]" keeps navbar header disabled

### ISSUE THREAD

**Issue by kshepherd** [DSpace/dspace-angular#3189] opened 2024-07-17 15:46 UTC
## Describe the bug
In DSpace 8.0, if you are logged in as an administrator and use the left-hand sidebar to click "Import" and then either of the two options (Metadata, Batch Import ZIP), the navbar / header links and buttons become disabled and are unable to be interacted with. Even a full page refresh will not re-enable these links. To clear it you must either proceed through the metadata import process, or try some other admin sidebar functions which load different pages and will reset the navbar enabled/disabled state.

It seems like something going wrong with responsiveness detection, perhaps the navbar thinks it is collapsed? The sidebar also doesn't auto-hide for some items, typically those that just go to a new dspace page without also popping up a selector modal (which do auto hide), but I'm not sure if that's related and so far, "Import" items are the only ones I have seen that cause the navbar / header to break. It happens whether or not the sidebar is pinned.

## To Reproduce
Steps to reproduce the
1. Log into a DSpace 8.0 site (e.g. demo.dspace.org) as an administrator
2. Reveal the left-hand sidebar menu, click Import and then click either Metadata or Batch Import (ZIP)
3. Try to click links in the breadcrumbs, header, login / profile dropdowns, etc. The cursor will remain as a 'pointer' and nothing can be interacted with.

## Expected behavior
The DSpace navigation and header links should all be active and working after clicking Import -> Metadata, just like other admin pages

**Comment by tdonohue** [comment] 2024-07-17 16:16
Thanks @kshepherd .  I can verify I see the same behavior on demo.dspace.org.  If you leave the page (e.g. by clicking the "Back" button), the header is usable again.  

So, I suspect it might just be that those pages (or more accurately a component on those pages) are somehow disabling the header or "drawing" something (invisible) over the header, so the header links/buttons can no longer be hovered over.

Moving this to our 8.x/7.x maintenance board.  Needs a volunteer.

**Comment by Andrea-Guevara** [comment] 2024-07-24 20:53
Good afternoon @tdonohue! My name is Andrea and I'm part of the Neki-it company. We have analyzed and seen that in the component “ds-file-dropzone-no-uploader” the classes “position-fixed h-100 w-100” are affecting the behavior of the navbar. We would like to contribute a solution to this problem.

**Comment by Andrea-Guevara** [comment] 2024-07-25 14:10
Good morning @tdonohue! We've provided a PR with the cause and solution to this problem.
https://github.com/DSpace/dspace-angular/pull/3220

We look forward to your feedback!

**Closed** 2024-08-01 13:46 UTC
Labels: bug, help wanted, tools: import, good first issue
