### ISSUE TITLE
Administrative edit of item miss the ability to deal with authority

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#823] opened 2020-07-30 13:36 UTC
In the previous versions of DSpace the administrator was able to edit metadata with authorities values both directly adding the "authority ID" than using a lookup. This feature is currently missing in the Angular UI

**Describe the solution you'd like**
Provide the same feature that was available in the previous version. For metadata that allow an authority ID to be stored aside the text value the UI should allow the admin to inspect, input and modify such value directly or use a lookup button to query the authority (vocabulary) to get a suggestion

**Additional context**
![Screenshot from 2020-07-30 15-33-58](https://user-images.githubusercontent.com/1537527/88929274-32e60580-d27a-11ea-906d-14c0ba8924d0.png)

**Comment by tdonohue** [comment] 2023-03-09 20:43
Moving this to the 7.6 board as it is a feature that existed in 6.x.  It could be claimed for 7.6 if anyone is interested.

**Comment by tdonohue** [comment] 2023-06-28 21:27
Closing as a duplicate of #1758 as that one has additional detailed screenshots.

**Closed by tdonohue** 2023-06-28 21:27 UTC
Labels: help wanted, new feature, component: administrative tools, medium priority, component: Item, component: authority control
