### ISSUE TITLE
Community-list page expand icons not automatically shown

### ISSUE THREAD

**Issue by samuelcambien** [DSpace/dspace-angular#899] opened 2020-10-16 09:33 UTC
When navigating to the community list page from another page, the expand icons are not automatically shown. They only appear after the change detection has been triggered somehow (eg by clicking somewhere). The issue doesn't seem to occur when loading the community list page directly.

To reproduce:
- Navigate to the DSpace home page
- Click on the "Communities & Collections" link in the "All of DSpace" section in the top menu
- Wait (don't click or interact with the page)

Expected behaviour:
- Expand icons should appear

Observed behaviour:
- Expand icons don't appear

**Comment by tdonohue** [comment] 2020-10-16 14:07
@samuelcambien : I'm not able to reproduce this on the demo site.  Here's what I'm doing (in Chrome browser):
1. Visit https://dspace7-demo.atmire.com/
2. Click "All of DSpace" -> "Communities & Collections"
3. Wait (making sure not to click on anything). It takes a moment, but the expand icons appear after a few seconds.

Is there something I'm overlooking here?  Or maybe this is a browser specific bug?

**Comment by saschaszott** [comment] 2020-10-17 15:20
Perhaps there is a related problem: if you open Communities & Collections directly (go to https://dspace7-demo.atmire.com/community-list), the result list is empty.

**Comment by tdonohue** [comment] 2020-10-22 18:59
Will be included as part of fix for #908.  Therefore, moving this to beta5 with a **zero hour** estimate.

**Closed** 2020-11-19 22:23 UTC
Labels: bug, component: Community, component: Discovery, e/0
