### ISSUE TITLE
Probably a caching issue for impersonate feature on an admin user

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/dspace-angular#1548] opened 2022-03-07 15:29 UTC
**Describe the bug**
After a user was created, as an admin I've assign him the admin profile and went to see the user profile.
![2022-03-07 15_09_45-DSpace Angular __ EPeople](https://user-images.githubusercontent.com/877488/157063265-f44cba6b-d126-44ad-8d02-a779ad0c3e6c.png)

Then I assign him the admin group
![2022-03-07 15_10_15-DSpace Angular __ Edit Group](https://user-images.githubusercontent.com/877488/157063281-0be6eb42-610f-4350-a4fb-ccc6acbe723d.png)

Back on the user profile page I was able to see actions that I think they don't apply for users in that profile
![2022-03-07 15_10_45-DSpace Angular __ EPeople](https://user-images.githubusercontent.com/877488/157063298-e0051155-26eb-4814-a98d-4ccd8e100a92.png)

**To Reproduce**
Steps to reproduce the behavior (I've used Firefox on Windows 10):
1. I sign in using shibboleth authentication. Then an account was created
2. Then I sign in as an administrator and visit the user profile firstly
3. Went to groups management and assigned the new user to the administrator group
4. On the users list, I went to see the eperson profile
5. On the eperson profile (the recently group data added wasn't yet available) the impersonate option was available and I click it. No visible error occurred **reload** action got stuck on the loading content (the dots animation).

**Expected behavior**
I think you couldn't impersonate another admin. If that's the case, then, the user profile should be updated with the required features and permissions/authorizations, also, it should display the recently groups added.

**Comment by tdonohue** [comment] 2022-05-09 15:51
Thanks @paulo-graca : I can reproduce this.

It looks like a caching issue to me.  The groups listing on the EPerson edit page is not reloading.

How to reproduce:
1. Edit an EPerson
2. Add them to a Group (any group)
3. Go back to that same EPerson Edit page.  Their group will not be listed.  However, if you reload the page (click browser's reload button), then the group will appear.

Moving this to 7.4 and flagging as high priority.

**Comment by artlowel** [comment] 2022-08-12 10:18
This will take an estimated **4 hours**
Atmire would like to claim it

**Comment by artlowel** [comment] 2022-08-24 12:09
@tdonohue While working on this issue we discovered two more related issues involving caching and the groups page:

1. if you delete the last member of a group, the members list will not update.
    - The reason is that the observableCombineLatests [here](https://github.com/DSpace/dspace-angular/blob/main/src/app/access-control/group-registry/group-form/members-list/members-list.component.ts#L147) and [here](https://github.com/DSpace/dspace-angular/blob/main/src/app/access-control/group-registry/group-form/members-list/members-list.component.ts#L277) will have no parameters if there are no members, so won't emit. This needs to be rewritten in a different way, to allow for empty result lists
2. If you've retrieved something first using its self link, then using an alternative link, and then set the self link request to stale, the original component won't switch over to the alternative link version, instead it will hang because it's observing a part of the store that will never be updated again (a stale request). 
    - After the fix for this original issue was put in place, we noticed this issue when we 
        - went to a group page (which will retrieve the group using its self link), 
        - then added a person, and went to their profile page (which will retrieve the group again, this time using the link on the eperson, an alternative link) 
        - and then back to the group page. That page would hang.
    - The culprit is this [observableRace](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/cache/builders/remote-data-build.service.ts#L210-L215), because the self link request will 'win' the first time, but afterwards the race is never run again. This needs to be replaced with a more sophisticated way of comparing requests

We can fix both these issues in an additional **10 hours**

**Comment by tdonohue** [comment] 2022-08-24 13:49
@artlowel: I agree that it makes sense to just solve all these issues together.  I'll bump the estimate on this ticket up to 14 hours & you can just fix these all together then.

**Comment by artlowel** [comment] 2022-10-20 09:44
Closing. This was fixed by #1808, but not linked up to the PR properly so not closed automatically

**Closed by artlowel** 2022-10-20 09:44 UTC
Labels: bug, help wanted, high priority, authorization, performance / caching, e/14
