### ISSUE TITLE
Testathon: Cannot click on communities in the home page sandbox

### ISSUE THREAD

**Issue by IgorBaptist4** [DSpace/dspace-angular#2952] opened 2024-04-17 17:15 UTC
**Describe the bug**
In the sandbox 8.0 homepage, in the section "Communities in DSpace" I'm not able to click in the link of the communities, sometimes I'm able to click only in the last one showed in the list. Tested in Chrome, Edge and Firefox. https://sandbox.dspace.org/

**To Reproduce**
1. Open the sandbox environment
2. Try to click in any of the communities on the section "Communities in DSpace"

**Expected behavior**
Redirect to the community page

**Comment by tdonohue** [comment] 2024-04-17 19:43
Duplicate of #2942.  This is the same bug described there. There's already a possible fix under review (#2945).

I'm closing this ticket in favor of #2942.  See that ticket for further updates.

**Closed by tdonohue** 2024-04-17 19:43 UTC
Labels: bug, needs triage
