### ISSUE TITLE
Error when Editing Groups: 'admin.access-control.groups.form.members-list.notification.failure' and 404 Not Found Exceptions in DSpace 7.6 with DSpace CRIS

### ISSUE THREAD

**Issue by DexterNinja** [DSpace/dspace-angular#3207] opened 2024-07-18 11:42 UTC
**Describe the bug**
I am currently using DSpace 7.6 with DSpace CRIS. I had recently installed it and am facing an issue while editing "Groups" using the administrator account. Whenever I try to edit the group, I get the pop-up error "admin.access-control.groups.form.members-list.notification.failure" and "Something went wrong: An exception has occurred" - screenshot attached.

**To Reproduce**

Log in as an administrator.
Navigate to Access Control.
Edit any group.
Observe the error message.

**Expected behavior**
The members list of the group should be displayed without any error.

**Error Log**

2024-07-18 17:12:21,282 INFO  32a679cb-8c40-4a77-ad68-dcd6b69ca794 c142f5bc-bcfa-44aa-a2d7-a9cf71507cf2 org.dspace.app.rest.utils.DSpaceAPIRequestLoggingFilter @ Before request [GET /server/api] originated from /access-control/groups
2024-07-18 17:12:21,309 INFO  32a679cb-8c40-4a77-ad68-dcd6b69ca794 1c3f9e96-dda2-4abc-acc4-2e33dcdbced7 org.dspace.app.rest.utils.DSpaceAPIRequestLoggingFilter @ Before request [GET /server/api/authz/authorizations/search/object] originated from /access-control/groups
2024-07-18 17:12:21,375 INFO  32a679cb-8c40-4a77-ad68-dcd6b69ca794 301d2bec-b1d0-4dde-9f51-14bd80bc1496 org.dspace.app.rest.utils.DSpaceAPIRequestLoggingFilter @ Before request [GET /server/api/eperson/epersons/search/isNotMemberOf] originated from /access-control/groups/7202ec8d-e1b9-466a-aed2-9d92031c789c/edit
2024-07-18 17:12:21,376 INFO  32a679cb-8c40-4a77-ad68-dcd6b69ca794 3f56003f-5e64-4f56-b704-407d87e83b0b org.dspace.app.rest.utils.DSpaceAPIRequestLoggingFilter @ Before request [GET /server/api/eperson/groups/7202ec8d-e1b9-466a-aed2-9d92031c789c/epersons] originated from /access-control/groups/7202ec8d-e1b9-466a-aed2-9d92031c789c/edit
2024-07-18 17:12:21,381 WARN  32a679cb-8c40-4a77-ad68-dcd6b69ca794 301d2bec-b1d0-4dde-9f51-14bd80bc1496 org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:404 exception: null at: org.dspace.app.rest.RestResourceController.executeSearchMethods(RestResourceController.java:992))
2024-07-18 17:12:21,383 INFO  32a679cb-8c40-4a77-ad68-dcd6b69ca794 7fe6b0be-0494-4fb8-b003-80270208b838 org.dspace.app.rest.utils.DSpaceAPIRequestLoggingFilter @ Before request [GET /server/api/eperson/groups/7202ec8d-e1b9-466a-aed2-9d92031c789c/subgroups] originated from /access-control/groups/7202ec8d-e1b9-466a-aed2-9d92031c789c/edit
2024-07-18 17:12:21,384 INFO  32a679cb-8c40-4a77-ad68-dcd6b69ca794 bfcb9610-03a3-4f5b-b332-749700ca8b7e org.dspace.app.rest.utils.DSpaceAPIRequestLoggingFilter @ Before request [GET /server/api/eperson/groups/search/isNotMemberOf] originated from /access-control/groups/7202ec8d-e1b9-466a-aed2-9d92031c789c/edit
2024-07-18 17:12:21,387 WARN  32a679cb-8c40-4a77-ad68-dcd6b69ca794 bfcb9610-03a3-4f5b-b332-749700ca8b7e org.dspace.app.rest.exception.DSpaceApiExceptionControllerAdvice @ An exception has occurred (status:404 exception: null at: org.dspace.app.rest.RestResourceController.executeSearchMethods(RestResourceController.java:992))

**Additional Information**
I thought the issue might be related to the database initialization, so I checked the status using ./dspace database status, and all of the databases reported success. What could be the issue?

Screenshots
![Error - Dspace Groups](https://github.com/user-attachments/assets/12c34881-4428-4a06-9798-7abec24fe58a)

**Environment**
DSpace version: 7.6
DSpace CRIS

**Steps Taken to Troubleshoot**
Verified database status.
Checked logs for errors.

Any insights or suggestions to resolve this issue would be greatly appreciated.

**Comment by tdonohue** [comment] 2024-07-18 21:00
Closing, as this is a request for support and not a bug ticket.  Here's a few suggestions.

First, DSpace-CRIS is a different product from DSpace.  DSpace-CRIS is *based on* DSpace, but it's a product of 4Science. See their wiki at https://wiki.lyrasis.org/display/DSPACECRIS

DSpace Support requests should be sent to one of the Support options at https://wiki.lyrasis.org/display/DSPACE/Support

DSpace also has a troubleshooting guide for how to find underlying error messages: https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

**Closed by tdonohue** 2024-07-18 21:00 UTC
Labels: bug, needs triage
