### ISSUE TITLE
Bug in Navigation - Current Members in Edit group page

### ISSUE THREAD

**Issue by DSquareTechnologies** [DSpace/dspace-angular#1127] opened 2021-04-25 14:53 UTC
**Describe the bug**
Upon clicking the User name link appearing on Edit groups page. The system is opening User groups page instead of Eperson profile page for the selected user.

**To Reproduce**
1. Login using Administrative credentials
2. Go to User Groups from Administration Panel - Access Control > Groups
3. Click on Edit button appearing next to any User group
4. Scroll down to Current Members table appearing on Edit group page
5. Click on any user name appearing with the hyperlink under Name column in this table
6. Next page that opens as a result of this action will be User groups list page

**Expected behavior**
If a user clicks on User name then it should open the Eperson profile page of selected Eperson.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment] 2021-04-26 20:56
@artlowel : assigning this to you for your team to analyze & estimate.  Looks like it might just be a broken/bad link in UI

**Comment by artlowel** [comment] 2021-04-27 15:39
The problem is that [whenever you navigate away from the edit groups page for any reason, its onCancel method is called](https://github.com/DSpace/dspace-angular/blob/main/src/app/access-control/group-registry/group-form/group-form.component.ts#L408), and that will [navigate back to to the groups list](https://github.com/DSpace/dspace-angular/blob/main/src/app/access-control/group-registry/group-form/group-form.component.ts#L211), overriding whatever navigation was in progress.

We can patch this in an hour, but it again makes it clear that those access control pages need redesign. We should assign #647 to a milestone.

Atmire will create a PR for this issue

**Comment by tdonohue** [comment] 2021-04-27 16:25
Thanks @artlowel .  I'll assign this back to your team. I've also scheduled #647 tentatively for 7.1

**Closed** 2021-05-07 14:42 UTC
Labels: bug, component: administrative tools, e/1, high priority, testathon
