### ISSUE TITLE
Search for a ePerson or Search for a group in the resource policies page doesn't work

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1544] opened 2022-03-02 11:20 UTC
**Describe the bug**
When adding a new resource policy to dspace object, it's not possible to Search for a ePerson or Search for a group.
Also, the Browse All button doesn't work and it's not possible to browse through the lists of ePersons and Groups by using the next page buttons.

**To Reproduce**
1. got to Edit item page
2. by the status tab click on Authorizations 
3. click on Add
4. Then try to use tha pagination to navigate the eperson/group list, or try to use the search and browse all buttons

**Expected behavior**
The pagination, search and browse functionality should work properly

**Comment by atarix83** [comment] 2022-03-02 11:52
@tdonohue 

this is a bit challenging to resolve because here the issue is due to the fact the `ResourcePolicyFormComponent` is initialized every time a pagination event is triggered (next/prev page, search or browse).
 
This is happening because in the [root.component](https://github.com/DSpace/dspace-angular/blob/main/src/app/root/root.component.html) the reouter-outlet is destroyed every time we show the [full screen loader](https://github.com/DSpace/dspace-angular/blob/8d953f8488ef4666cbaab434bace11975787a025/src/app/root/root.component.html#L1). 

In my opinion destroying the reouter-outlet should be avoided in order to avoid the components are initiliazed many times even if we navigate to the same route but just with pagination params, how it's happening in the case of the bug reported.

Maybe we can fix by using the same approach of hiding the reouter-outlet instead of destroying it, how it's been done [when we show the route loader](https://github.com/DSpace/dspace-angular/blob/8d953f8488ef4666cbaab434bace11975787a025/src/app/root/root.component.html#L18)

@artlowel  do you agree? do you see some side effects related to the dynamic theming system?

**Comment by artlowel** [comment] 2022-03-02 13:34
I agree, hiding the outer-wrapper div (which contains the outlet) will be more efficient than removing it. I don't see how this should affect theme switching, but it's best to do a test with a few different themes on different routes after the change to make sure.

**Comment by tdonohue** [comment] 2022-03-02 14:49
This appears to be a duplicate of #1516 , which was reported a few weeks back.

Nonetheless, I'd love to see this fixed ASAP.  So, if someone wants to claim this, please let me know & provide an estimate.

**Comment by atarix83** [comment] 2022-03-02 18:00
@tdonohue 

we can work on this, the fix could be easy to apply but we need to try if it has impact on the theming so I'd give an estimation from 2 hours to 6 hours in case the fix has unexpected side effects

**Comment by tdonohue** [comment] 2022-03-02 21:10
Sounds good, @atarix83 . Assigning to you. Will add the middle estimate of **4 hrs** to this ticket, but I know it may be a few hours over if there's side effects.

**Closed** 2022-04-26 20:11 UTC
Labels: bug, high priority, authorization, e/4
