### ISSUE TITLE
Reloading Community page results in TypeError

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#223] opened 2018-02-08 18:00 UTC
On latest master (running Angular 5) this error can be seen.  I'm using Windows 10.

How to Reproduce:
* Startup the app (e.g. `yarn start`). 
* Visit a community page, e.g. http://localhost:3000/communities/7669c72a-3f2a-451f-a3b9-9210e7a4c02f
* Click the reload button in your browser

On the console, an error similar to this will appear:
```
TypeError: Cannot convert undefined or null to object
    at e.t.flattenSingleKeyObject (D:\programming\dspace-angular\dist\server.js:1:1081312)
    at e.parse (D:\programming\dspace-angular\dist\server.js:1:546606)
    at MapSubscriber.project (D:\programming\dspace-angular\dist\server.js:1:1133398)
    at MapSubscriber._next (D:\programming\dspace-angular\node_modules\rxjs\operators\map.js:79:35)
    at MapSubscriber.Subscriber.next (D:\programming\dspace-angular\node_modules\rxjs\Subscriber.js:90:18)
    at CatchSubscriber.Subscriber._next (D:\programming\dspace-angular\node_modules\rxjs\Subscriber.js:126:26)
    at CatchSubscriber.Subscriber.next (D:\programming\dspace-angular\node_modules\rxjs\Subscriber.js:90:18)
    at MapSubscriber._next (D:\programming\dspace-angular\node_modules\rxjs\operators\map.js:85:26)
    at MapSubscriber.Subscriber.next (D:\programming\dspace-angular\node_modules\rxjs\Subscriber.js:90:18)
    at FilterSubscriber._next (D:\programming\dspace-angular\node_modules\rxjs\operators\filter.js:89:30)
```

However, the Community page loads successfully in the browser with seemingly no adverse effects from this backend error.

This error seems to only occur when reloading Community pages.  Reloading the homepage, Collection pages or Item pages does not result in any errors.

**Comment by tdonohue** [comment] 2018-02-12 15:48
NOTE: This issue and #224 may be related, as the errors are very similar

**Comment by artlowel** [comment] 2018-02-15 13:24
That is indeed due to [this collection](https://dspace7.4science.it/dspace-spring-rest/api/core/collections/37080328-3aa0-442f-86f5-5ff75434fd5f/logo) having a logo in its `_links` section, but [that logo returning an empty response](https://dspace7.4science.it/dspace-spring-rest/#https://dspace7.4science.it/dspace-spring-rest/api/core/collections/37080328-3aa0-442f-86f5-5ff75434fd5f/logo). 
Closing this issue as a duplicate of #224

**Closed by artlowel** 2018-02-15 13:24 UTC
Labels: bug
