### ISSUE TITLE
Cancelling after giving focus to Processes select dropdown, but not selecting a script, incorrectly generates an error

### ISSUE THREAD

**Issue by J4bbi** [DSpace/dspace-angular#3066] opened 2024-05-21 15:15 UTC
**Describe the bug**
On DSpace 8.x when selecting a new process, if you do not select one, and either click outside the select drop down or select the default "Choose a script..." option and then click the Cancel button, an error is generated: "Script is required".

Interestingly, this only happens the first time the button is clicked. If you then click it a second time, you are redirected back to the Processes overview page.

**To Reproduce**
1. Login in as administrator (for example on https://demo.dspace.org/)
2. Select processes from the left hand admin menu to go to the Processes overview page
3. Select New+
4. Select the dropdown
5. Either select "Choose a script..." or click outside the drop down
6. Select Cancel

![image](https://github.com/DSpace/dspace-angular/assets/5488106/48aac126-81c1-44d6-ba5f-46cd37b9a0df)

**Expected behavior**
Pressing Cancel should redirect the user back to the processes overview page regardless of what he selects in the dropdown.

**Comment by tdonohue** [comment] 2024-05-21 16:10
@J4bbi : I'm not able to reproduce this on either our Demo Site (https://demo.dspace.org, running 7.x) or Sandbox Site (https://sandbox.dspace.org, running pre-8.0)

Here's what I see:
1. Login in as administrator (for example on https://demo.dspace.org/)
2. Select processes from the left hand admin menu to go to the Processes overview page
3. Select New+
4. Select the dropdown
5, Either select "Choose a script..." or click outside the drop down.   (I can verify this shows the "Script is required" message that you shared a screenshot of)
6. Select Cancel.  (For me, the "Cancel" button works in both 7.x and 8.0.  It sends the user back to the Processes Overview page.)

Maybe this bug was in an earlier version of DSpace 7?  Perhaps it's already been fixed in the latest code, which is why it's not reproducible on the Demo site or Sandbox Site.    

Or, maybe you are using a different browser?  I'm testing in latest Chrome (124.0.6367.208 (Official Build) (64-bit))

**Comment by alexandrevryghem** [comment] 2024-05-21 18:46
This was fixed [here](https://github.com/DSpace/dspace-angular/commit/52c0977489063689dba99caf004e4120a85e9fc9#diff-d76a1ef68bec8ba9b5743ea3c0f6c6b4e80b42a35f5352bc42fb39962313f7f5R10) (PR #2683 & backport PR #2696) by changing the `<button>` to a `<a>` link

**Comment by tdonohue** [comment] 2024-05-21 18:54
Thanks for verifying, @alexandrevryghem !  In that case, closing this as fixed in 7.6.2 and 8.0

**Closed by tdonohue** 2024-05-21 18:54 UTC
Labels: bug, Difficulty: Low, good first issue, needs triage, tools:processes
