### ISSUE TITLE
Getting 401 when Community or Collection Administrator tries to edit Collection Authorization Group

### ISSUE THREAD

**Issue by ttornyai** [DSpace/dspace-angular#927] opened 2020-10-29 16:19 UTC
Description:
When a Community Administrator tries to edit a Collection's authorization Group (for example Submitters), then the site navigates to a 401 Unauthorized site. The user can create or delete these groups tho.
The problem occurs on the beta4 version of both dspace, and dspace-angular, in Chrome browser (86.0.4240.111).

1. Create a Community with site admin (the one, created with the 'dspace create-administrator' command), and create a Collection inside it
2. Create an Administrators authorization group in the corresponding Community
3. Create an EPerson through normal registration (with email link)
4. With the site admin, add the created user to the Administrators group (which we created in step 2)
5. Sign in with the created user, and create a Submitters group in the Collection inside the Community (in the 'assign roles' tab in the 'edit' page of the Collection) (it gets created)
6. Try to edit the group (through the link in the 'assign roles' tab in the 'edit' page of the Collection) 

Expected behavior:
The site navigates to the group editing page where I can add users to the submitters group

**Comment by LucaGiamminonni** [comment] 2020-10-30 15:10
Perhaps the bug could be solved with the changes made in the PR [3034](https://github.com/DSpace/DSpace/pull/3034)

**Comment by tdonohue** [comment] 2020-10-30 15:38
I'm able to reproduce this as **both a Collection Admin or a Community Admin**.  _It seems unrelated to the backend PR https://github.com/DSpace/DSpace/pull/3034_.

The 401 error appears to be entirely **client side**. In Chrome dev tools, I do not see a corresponding request/response to/from the REST API when this error is shown.  In this situation the Collection/Community Admin appears to not be allowed to access the Edit Group path of `http://localhost:4000/admin/access-control/groups/[uuid]` (which is the URL you have to go to in order to actually edit a group).

Could it be that the `/admin` path is simply access restricted to Site-wide Admins?  @artlowel or @atarix83 any ideas on this one?

**Comment by artlowel** [comment] 2020-10-30 16:24
>Could it be that the /admin path is simply access restricted to Site-wide Admins?

That's indeed the case, it's behind a guard that checks whether you're a sitewide admin: https://github.com/DSpace/dspace-angular/blob/main/src/app/app-routing.module.ts#L50

**Comment by artlowel** [comment] 2020-11-04 10:35
In that case I'd prefer to move it out of the `/admin` route, and add a more suitable guard for the access control pages. The other pages under the `/admin` route are the [metadata](https://dspace7-demo.atmire.com/admin/registries/metadata) and [bitstream-format](https://dspace7-demo.atmire.com/admin/registries/bitstream-formats) registries, the [admin search](https://dspace7-demo.atmire.com/admin/search) and the [admin workflow](https://dspace7-demo.atmire.com/admin/workflow) page. Do any of those need to move as well?

**Comment by tdonohue** [comment] 2020-11-04 14:35
@artlowel : I'd recommend keeping this ticket scoped to the Group editing issues.  So, leave all other `/admin` pages as-is...(As a sidenote, I believe they are all in the correct place, as those look to be pages that only Site Administrators should be able to access.)

For the purposes of this ticket, I'd recommend we just move the `/admin/access-control/groups` path to be at `/access-control/groups` (or similar) and ensure that path is accessible to Site Admins, Community & Collection Admins.  Would you be able to provide an estimate for this effort?

**Comment by artlowel** [comment] 2020-11-05 11:08
To do this properly we'd need changes to the rest api. 

Currently the only way I can find to check if someone is a community or collection admin is to check the administratorOf feature for the eperson against all communities and collections, to see if you get a result. One way around this could be to make the `uri` parameter optional on [the `/authorizations/search/object` endpoint](https://github.com/DSpace/Rest7Contract/blob/main/authorizations.md#search-methods). That way it could return all the objects an eperson is the adminsitrator of, but I realize that this might not be feasible on the rest side due to performance issues.

An alternative could be to provide a dso-type instead of a uri to that search endpoint which would return an authorization if you're an admin for any of the object that have the given type. But again, that may have the same performance impact 

So the best we can do right now is to move it to a new route and allow all authenticated users to access it. Doing so would take an estimated **2h**

**Comment by tdonohue** [comment] 2020-11-05 17:33
Thanks for the summary of options here, @artlowel .

I think you are correct that we have a missing "feature" check on the REST API.  It seems the `administratorOf` feature is limited in that it can only check Community/Collection Admin permissions _on a specific object_. 

What we need is a way to ask the REST API "does this user have Admin permissions on ANY community or collection".  We **already have that check** available in our Java API in [`AuthorizeService.isCommunityAdmin()`](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/authorize/AuthorizeServiceImpl.java#L431) and [`AuthorizeService.isCollectionAdmin()`](https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/authorize/AuthorizeServiceImpl.java#L451).

So, in my opinion, what you pointed out means we need 1-2 new Feature endpoints, e.g. `isCollectionAdmin` and `isCommunityAdmin` which do NOT require an object to be passed in, but return the result of those AuthorizeService methods linked above.

@benbosman or @abollini : Would you agree with this approach of adding a new Feature endpoint here?  My guess is this would only be an extra 2 hours of effort, and would allow us to properly access restrict the `/access-control/groups` page in the UI to only individuals who have Community or Collection admin access. Thoughts?

**Comment by abollini** [comment] 2020-11-10 08:33
@tdonohue  I'm ok with adding more specific features to simplify the implementation of the UI guard and to avoid performance issue I agree that we need something specific that just tell us yes or no instead than trying to get the list of collections or communities where the action is possible. That said, in such case I think that we need a canManageGroups feature because it is possible that a community or collection admin cannot manage groups (see AuthorizeUtil). As there are many edge scenario the test could be a bit more sophisticated and I would suggest a 4 hours estimation

**Comment by tdonohue** [comment] 2020-11-18 21:59
Thanks for the estimates here @abollini and @artlowel. I've updated this ticket with an estimate of *6 hours* (4hr for backend/REST API and 2hr for Angular UI cleanup after that is done.)

**Comment by tdonohue** [comment] 2021-01-07 17:55
@benbosman , @artlowel and @abollini :  Just stumbled on this old JIRA ticket which seems to align with some of what @benbosman and @artlowel were noting in today's meeting: https://jira.lyrasis.org/browse/DS-4505    It sounds like we discovered this earlier and forgot about it...so, the suggested approach of looking towards indexing this information in Solr might be necessary.  I just wanted to link in this old JIRA ticket as it describes one implementation approach.

**Comment by benbosman** [comment] 2021-01-08 10:06
This is indeed in line with what I would expect here.
I've updated the status of this issue, and will update it with my input next week

**Comment by benbosman** [comment] 2021-01-12 11:49
@tdonohue I've read through all the details in this ticket, and found 3 parts requiring support in REST. The code for all these parts is quite common.
Could you please read through this to verify whether you agree with the suggestion, I'll make an estimate if you agree with these specs:

### Goal 1:
Check if someone is a community or collection admin without iterating all communities and collections in either Angular or REST

**REST endpoint and call to use:**
Search /api/authz/authorizations/search/object?uri=<:uri>[&eperson=<:uuid>&feature=<:string>] using:
* uri: the site uri
* feature: isCommunityAdmin, isCollectionAdmin, isComColAdmin

**Backend implementation:**
AuthorizeService.isCommunityAdmin() and AuthorizeService.isCollectionAdmin() can cause scalability issues

To avoid scalability issues, it's possible to create a discovery plugin similar to SolrServiceResourceRestrictionPlugin and SolrServiceIndexCollectionSubmittersPlugin, but verifies whether the user has admin rights
A search is performed whether at least one such community or collection exists


### Goal 2:
Check if someone can manage groups for a community or collection admin without iterating all communities and collections in either Angular or REST (to determine whether the current user can open /admin/access-control/groups)

**REST endpoint and call to use:**
Search /api/authz/authorizations/search/object?uri=<:uri>[&eperson=<:uuid>&feature=<:string>] using:
* uri: the site uri
* feature: canManageGroups

**Backend implementation:**
AuthorizeService.isCommunityAdmin() and AuthorizeService.isCollectionAdmin() can cause scalability issues

To avoid scalability issues, it's possible to extend the above discovery plugin to also store whether the user has manage groups rights
A search is performed whether at least one such community or collection exists


### Goal 3:
Get the list of all communities and collections the current user is admin for, using search, without iterating all communities and collections in either Angular or REST (to navigate to the edit community or edit collection page)

**REST endpoint and call to use:**
New endpoints to create (similar to [findSubmitAuthorized](https://github.com/DSpace/Rest7Contract/blob/main/collections.md#findsubmitauthorized)):
* /api/core/collections/search/findAdminAuthorized
* /api/core/communities/search/findAdminAuthorized

The discovery plugin mentioned above can be used without further changes

**Comment by tdonohue** [comment] 2021-01-12 15:12
@benbosman : Yes, those goals sound correct to me.  A few minor notes about the first two goals:

**Goal 1**
The indexing logic needed here seems to already be in `SolrServiceResourceRestrictionPlugin` at: https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/discovery/SolrServiceResourceRestrictionPlugin.java#L105-L122   

So, we may not need a separate plugin. It might be easy to simply update that plugin to indexing ADMIN permissions both as "read" and as "admin", i.e. add something like this around line 118:
```
 document.addField("admin", fieldValue);
```

**Goal 2** does not sound like it should need any additional indexes beyond what you are adding for Goal 1. In other words, the feature `canManageGroups` should really just check (1) if you are an Admin, or (2) if you have "admin" indexed permissions on at least one Collection or Community.  So, I don't believe this needs to have a separate index, but it should simply query the index you are adding in Goal 1 (i.e. I don't believe we need to store in Solr anything called "canManageGroups"... it seems like the "admin" index should be good enough here)

**Comment by benbosman** [comment] 2021-01-18 09:25
@tdonohue For **Goal 1** the SolrServiceResourceRestrictionPlugin only indexes READ permissions. It would be possible to use the same Plugin, but the plugins are intended to be light-weight and easy to read and maintain.
Most of the work will also be spent on creating ITs, so the difference in work for creating a separate plugin vs increasing the responsibilities of 1 plugin are negligible.

For **Goal 2**, I did suggest a separate index based on Andrea's comment https://github.com/DSpace/dspace-angular/issues/927#issuecomment-724548815 that it may be possible that group management is e.g. not allowed for collection admins

**Comment by tdonohue** [comment] 2021-01-19 15:13
@benbosman : 
For **Goal 1**, it seems a bit silly to me to loop through the same set of ResourcePolices in two separate plugins.  I do realize they are meant to be small, but it's more logical to me to loop through the ResourcePolicies *once*. It also helps with performance slightly to avoid duplicative loops in several plugins...especially since that loop climbs the hierarchy of objects, see https://github.com/DSpace/DSpace/blob/main/dspace-api/src/main/java/org/dspace/discovery/SolrServiceResourceRestrictionPlugin.java#L123 

I'm OK with moving this loop to a separate plugin though as you see fit.  For instance we could restructure this as `SolrServiceResourceReadPlugin` which only indexes `Constants.READ`, and `SolrServiceResourceAdminPlugin` which only indexes `Constants.ADMIN` (but it'd index it both as "read" and "admin" permissions).

For **Goal 2**, not sure if I'm misunderstanding...but my assumption here is that Collection Admins would have "admin" permission on the Collection object they administer.  This would be identical to the "canManageGroups" feature, as "canManageGroups" *requires* "admin" on the related object (Site, Community or Collection).  So, that's why it seems silly to me to index "canManageGroups" separately, as it seems like its index would be identical to "admin" indexed permissions.  If I'm incorrect (that the two indexes are not identical), then obviously we'd need two separate indexes here.

**Comment by benbosman** [comment] 2021-01-19 17:24
Hi @tdonohue We can work with the single loop for both READ and ADMIN permissions
I don't know for sure about the manage group permissions, we don't use the config to disable group editing permissions for collection/community admins. But since you're convinced that should work, I'll assume it should be fine.

Based on this, I'd estimate 6-8 hours of REST work
We have availability left to work on this

**Comment by artlowel** [comment] 2021-02-11 14:36
In order to use these features in angular we'll
- move access control out of the admin module
- create guards for the new features
- use them on the appropriate routes
- use the features to show and hide the sidebar menus and edit buttons

This will take an estimated **6h**

This is higher than [my previous estimate](https://github.com/DSpace/dspace-angular/issues/927#issuecomment-722308978) as that only dealt with moving access control.

Atmire is interested in claiming this ticket

**Comment by tdonohue** [comment] 2021-02-11 16:17
@artlowel : Thanks, that Angular estimate sounds fine.  I've added that to the initial REST estimate (of 8hrs) and changed this ticket to 14 hours total.  I've also added you as an additional assignee to start work on this.

**Closed** 2021-04-01 18:47 UTC
Labels: authorization, bug, e/14
