### ISSUE TITLE
Indent in the Abstract and Definition

### ISSUE THREAD

**Issue by SrinivasRao17** [DSpace/dspace-angular#1565] opened 2022-03-18 09:18 UTC
Dear Team,

When we import glossary terms into DSpace 7.1 version we are getting Indent in the Abstract and Definition. Please let me know what could be the possibilities chances to clear those spaces before Abstract and Definition. Thanks!!

Regards,
Srinivas Rao

**Comment by tdonohue** [comment] 2022-03-21 13:49
Closing, as not enough information is provided to reproduce the issue.  The issue doesn't appear to be reproducible on our demo site (at least I'm not seeing obvious indentations on abstracts, e.g. https://demo7.dspace.org/entities/publication/12623672-25a9-4df2-ab36-699c4c240c7e)

Therefore I suspect this is either a local data issue or a configuration issue, as it doesn't appear to be a bug.  If you need help with an issue that is not a bug, please use one of our Support options documented at https://wiki.lyrasis.org/display/DSPACE/Support

**Closed by tdonohue** 2022-03-21 13:49 UTC

**Comment by SrinivasRao17** [comment] 2022-03-21 14:00
![Abstract](https://user-images.githubusercontent.com/101823122/159276984-d120a632-f112-4fa7-bd01-12d5e1d23492.JPG)

I have uploaded a screenshot of the issue. You can see before description there is an space in start. Please let me know if you required any further information.

**Comment by tdonohue** [comment] 2022-03-21 14:02
@SrinivasRao17 : I cannot reproduce that on our demo site (demo7.dspace.org).  So, it seems like there's something different in your setup?  That's why I closed this as not being a bug in DSpace...we need to be able to reproduce the issue in a different DSpace site, and currently I've not been able to figure out a way to do so.

**Comment by SrinivasRao17** [comment] 2022-03-21 14:05
![Abstract 1](https://user-images.githubusercontent.com/101823122/159277873-c18a428e-93d2-4df8-895a-9e5c44cb0696.JPG)
before start of abstract "description" there is an space generated in our DSpace 7.1 version

**Comment by tdonohue** [comment] 2022-03-21 14:38
@SrinivasRao17 : Again, we are not able to reproduce this on our demo site (which is running DSpace 7.2), so maybe it's something that was fixed in 7.2?  Or maybe you've customized your DSpace in some way...perhaps even a CSS style customization... which is causing this to appear on your site?  

Since we cannot reproduce the issue, it's not something that can be fixed on our end. You may need to either upgrade to 7.2, or check your CSS styles to make sure they are not causing the indentation to occur.
