### ISSUE TITLE
search results not displayed while searching external sources

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/dspace-angular#997] opened 2021-01-25 17:59 UTC
**Describe the bug**

When a search against external sources is performed in order to import data from them, results are found but not correctly displayed in the UI

**To Reproduce**
1. log in into DSpace
2. Go to "MyDspace" section
3. start a submission from an external source
4. select source and enter a query string
5. if results are found, no data are displayed

![Schermata da 2021-01-25 18-49-20](https://user-images.githubusercontent.com/70699836/105746134-5ba43a80-5f3f-11eb-8a23-d5dd337db5cf.png)

**Expected behavior**
Result data returned by dspace rest correctly displayed

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment] 2021-01-25 18:21
I was able to verify this locally...something must have broken recently as this used to work.  Moving it to Beta 5 for analysis.  @artlowel would you be interested in providing an estimate for this (since it seems like it's UI-related)?

**Comment by atarix83** [comment] 2021-01-26 08:05
The problem is only on missing import of the modules that contains the loadable components, I'll fix quickly in a new PR

**Closed** 2021-02-05 15:31 UTC
Labels: bug, tools:external-sources
