### ISSUE TITLE
Cannot pagination or search groups when creating new resource policy

### ISSUE THREAD

**Issue by mspalti** [DSpace/dspace-angular#1516] opened 2022-02-11 00:59 UTC
**Describe the bug**
When creating a new resource policy, it's not possible view the available groups (and probably also available users) beyond the first set. When you use the pagination widget to advance to the next set, the "Create new resource policy" just page reloads. The same thing happens when you try use the Search option.

**To Reproduce**
1. Edit the authorizations for an item
2. Select the Add option
3. Scroll down and select "Search for a group" or "Search for ePerson"
4. Assuming the list is long enough, use the pagination widget to view the next page
5. Alternately, try using the search option
6. The page will reload

**Expected behavior**
You should see the next set of users/groups when browsing or a set of results when searching

**Comment by tdonohue** [comment] 2022-02-11 14:44
Thanks for reporting @mspalti .  I was able to reproduce this on demo7.dspace.org as well.  It looks recent & unfortunately rather serious since you cannot create a new Group based ResourcePolicy.

@artlowel or @atarix83 : Are either of you interested in looking into this for 7.3? At a glance, it looks to me like it is a UI-bug

**Comment by tdonohue** [comment] 2022-03-02 21:11
Closing, as this was duplicated into  #1544, and that other ticket has already been assigned/estimated.  So, #1544 replaces this ticket.

**Closed by tdonohue** 2022-03-02 21:11 UTC
Labels: bug, high priority, authorization
