### ISSUE TITLE
Approver/Editor not receiving Items for verification during submission

### ISSUE THREAD

**Issue by DSquareTechnologies** [DSpace/dspace-angular#1142] opened 2021-05-01 07:46 UTC
**Describe the bug**
User assigned as Editor and/or Reviewers in a collection does not receive item submitted in that collection for approval/editing.

**To Reproduce**
1. Create a collection
2. Go to Assign roles under Collection Administration
3. Add group under "Editors" and/or "Reviewers" section and add user in these groups. Please refer to Collection id: https://demo7.dspace.org/collections/65abd30f-1250-4d4c-b358-d4f0df4a972a where users are added in referred heads.
4. Submit an Item in the collection
5. You will notice no item appears in "My DSpace" section of the user(s) added as Editors/Reviewers.

**Expected behavior**
User assigned as Editor/Reviewer should be able to see and perform Editing/approval tasks on items submitted in the collection.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment] 2021-05-03 18:15
@DSquareTechnologies : I'm not able to reproduce this issue.  Here's what I see:

1. Setup a Collection as you describe, with at least one Editor or Reviewer
2. Submit a document to that collection
3. Login as the "Editor" or "Reviewer".  Visit their "My DSpace" page. 
4. Nothing will be displayed in the "Your Submissions" view. But, if you change the "Show" dropdown to say "All Tasks", you'll see the workflow tasks available to claim (including the one for the newly submitted document).

I suspect this was a misunderstanding about how to find workflow tasks, but let me know if I misunderstood the issue you are seeing.

**Comment by DSquareTechnologies** [comment] 2021-05-04 00:41
Hi Tim,

Let me follow steps and confirm you soon.

Thanks,

Narendra

**Comment by tdonohue** [comment] 2021-05-26 14:55
Closing, as this has been unreproducible. If it's able to be reproduced at a later date, we can reopen with additional information.

**Closed by tdonohue** 2021-05-26 14:55 UTC
Labels: bug, cannot reproduce, needs triage, testathon

**Comment by DSquareTechnologies** [comment] 2021-05-30 04:53
Hi Tim, 

Apologies response was skipped from my side. Affirmative, its working the way you shared. However, there is another issue identified. Unable to read detailed metadata and attachments while trying to approve/reject an item. Ccreenshots of process followed available on below link. Happy to open separate ticket if this is a bug.

https://drive.google.com/file/d/1nkswjwzullhEqObbFteP8aPjilf14EDN/view?usp=sharing

**Comment by tdonohue** [comment] 2021-06-16 15:49
@DSquareTechnologies : I've moved that into a separate ticket, see #1236
