### ISSUE TITLE
Attachment disappearing during submission process

### ISSUE THREAD

**Issue by DSquareTechnologies** [DSpace/dspace-angular#1218] opened 2021-05-30 12:00 UTC
**Describe the bug**
Attachment added at the beginning of the submission process gets disappeared automatically upon clicking 'I confirm the license above' checkbox under the deposit license section appearing at the bottom of the submission form and the deposit button remains disabled. When added another attachment in the same submission, the earlier attachment starts appearing again. 

DSpace version 7 beta 5 release, web browser - Chrome. Testing done on DSpace 7 demo site and video link for replicating error listed below.

**To Reproduce**
Please follow the steps recorded in the video link shared below:
https://youtu.be/eS7r-nc7F_U

**Expected behavior**
Attachment added in the submission form should not disappear upon checking to 'I confirm the license above' checkbox under deposit license section and deposit button should get activated.

**Comment by tdonohue** [comment] 2021-06-01 14:59
Closing, as this is a duplicate of #1144 and #1121.  This issue is being worked on and will be fixed in #1201 (currently under review)

**Closed by tdonohue** 2021-06-01 14:59 UTC
Labels: bug, duplicate, needs triage
