### ISSUE TITLE
Editing collection or item by admin menu, all the collections and items are listed despite the collection the user administers

### ISSUE THREAD

**Issue by GraziaQuercia** [DSpace/dspace-angular#2975] opened 2024-04-23 07:56 UTC
If I log in as a collection administrator, I can see that I am an administrator of Sample Collection. But, if I click on Edit in the administrative menu, it seems I have the chance to edit all the items and collections.
If I try to edit a non-administered collection or item, I get a 403 error.

How to reproduce:
- Go to DSpace 8 sandbox
- Log in as a collection administrator
- Go to profile and check which collection you administer (it is Sample Collection)
- Move to the left administrative menu
- click on Edit, then Collection (or item)
- A full list of collections (or items) is shown
![Screenshot 2024-04-23 093722](https://github.com/DSpace/dspace-angular/assets/124360978/7f3095e6-7b90-4bbf-bc2c-aa05bc2dd9ce)

- Click on one the collection administrator doesn't administer
- Get a 403 error
![Screenshot 2024-04-23 093736](https://github.com/DSpace/dspace-angular/assets/124360978/b7694d75-1ac5-452a-b34a-1fa2411df581)

This does not happen if we try to edit the administered collection, correctly
![Screenshot 2024-04-23 093755](https://github.com/DSpace/dspace-angular/assets/124360978/6be534b8-6c88-4ba5-bfa6-108f52be7385)

*Expected behaviour*
When a collection administrator starts the edit from the administrative menu, the only collections and items listed should be the ones administered.

**Comment by alexandrevryghem** [comment] 2024-04-23 08:43
Closing this as a duplicate of #1331

**Closed by alexandrevryghem** 2024-04-23 08:43 UTC
Labels: bug, needs triage
