### ISSUE TITLE
Breadcrumbing not showing on item pages on first page load

### ISSUE THREAD

**Issue by cwilper** [DSpace/dspace-angular#982] opened 2021-01-08 15:05 UTC
**Describe the bug**
If you visit an item page via URL, so it's the first URL visited for the site, breadcrumbing sometimes does not appear in the page initially. Reloading the page sometimes fixes it.

Example: https://imgur.com/a/4BJ2tEp

**To Reproduce**
1. Go to any item page directly in your browser, e.g.: https://dspace7-demo.atmire.com/items/37231e40-801c-47ab-a223-814c378fec4a . If breadcrumbing shows initially, reload the page until breadcrumbing doesn't show.
3. Click Full item page button and note that breadcrumbing immediately displays
5. Click Simple item page button and not that breadcrumbing continues to be displayed

**Expected behavior**
It should show breadcrumbing on intitial page load.

**Comment by tdonohue** [comment] 2021-01-21 21:03
@cwilper : I *believe* this is a duplicate of #976 .  As noted there, we've found odd breadcrumb behaviors as not all pages are setting the page title / breadcrumb.  So, I think we might be able to close this as a duplicate, unless I'm misunderstanding.

**Comment by artlowel** [comment] 2021-01-22 08:24
@tdonohue I don't think it's a duplicate. #976 deals with breadcrumbs not being configured. This ticket deals with an issue where a breadcrumb that _is_ configured doesn't always show up on the first page load. I'll assign myself to put an estimate on it

**Comment by artlowel** [comment] 2021-03-04 11:09
This will take **1h** to fix.

Atmire would like to claim this task

**Comment by artlowel** [comment] 2021-03-04 14:30
I spoke too soon. I quickly tried my idea, and while it makes the problem less likely to occur, it doesn't get rid of it entirely. So better bump this up to **4h** so we can investigate further

**Closed** 2021-03-22 19:44 UTC
Labels: bug, e/4
