### ISSUE TITLE
Recent Submissions pagination is not reloading properly

### ISSUE THREAD

**Issue by tantz001** [DSpace/dspace-angular#680] opened 2020-05-21 18:51 UTC
When browsing a collection with more than one page, advancing to another (next or previous) page does not work.  The page indicator moves as expected, but the items on the page do not change.  In addition, mousing over the items results in a 'flicker' as if some sort of mouseover event is being handled.  A page refresh results in proper display.  Tested on chrome, safari, edge, and firefox with the same results.

UPDATED DESCRIPTION (Based on comments below):
The problem seems to be in the "Recent Submissions" listing of a Collection.  Pagination is not working properly as the second page is never loaded when clicking on next page.

How to reproduce:
* Find a Collection with more than one page of "Recent Submissions". For example, this collection on the demo site: https://dspace7-demo.atmire.com/collections/8ad84c46-bdf1-4558-9b90-5c43ff396980
* Click on page 2 (or next page).  You will remain on the first page of items even though the screen looks to reload.
* If you click the reload button in your browser, you when then jump to the second page of items.

**Comment by tdonohue** [comment] 2020-05-27 21:04
@tantz001 : Could you describe how to reproduce this?  What do you mean by a "collection with more than one page"?

**Comment by tantz001** [comment] 2020-05-27 21:13
No, sorry, I mean a collection with more than a page full of items.  The behavior I see, when for example I go from page 1 to page 2 of such a collection, is that the page indicator moves, but the list of items remains the same -- with the added twist of the 'flicker'.  A simple (browser) reload/refresh of the page results in the correct page of items.  And yes, just like the url you included noted in your comment.  Apologies if this is a known issue, I didn't notice it!

**Comment by tdonohue** [comment] 2020-05-28 16:08
@tantz001 : I've updated the description & title of this ticket to better describe the bug. Thanks for locating it.  In the future, as noted, please provide steps to reproduce the bug, including links to the demo site (if reproducible there).  That makes it a ton easier on me to determine whether this bug is a duplicate or new bug. In this case, this appears to be a new bug.

**Comment by tdonohue** [comment] 2020-10-15 13:50
This was previously estimated in #854 (which was a duplicate of this ticket).  Copying over the estimate of **3 hrs** from that other ticket.

**Comment by AndrewZWood** [comment] 2021-01-05 17:53
I have a PR for this issue here: https://github.com/DSpace/dspace-angular/pull/979

**Comment by tdonohue** [comment] 2021-01-05 19:44
@AndrewZWood : Please link together the PR with this issue ticket by using one of GitHub's keywords (e.g. Saying `Fixes #980` in the PR description will link them). See docs at https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

(I wanted to call this out as I sometimes have to do this for developers who forget to use these keywords...it's much easier if you can get in the habit of using one of those keywords that triggers GitHub to link the PR to the issue automatically.  Thanks!)

**Comment by AndrewZWood** [comment] 2021-01-05 20:26
@tdonohue Done and I will do such in the future. Thank you for pointing that out to me.

**Closed** 2021-01-27 16:18 UTC
Labels: bug, component: Discovery, e/3
