### ISSUE TITLE
issue with listing all collection in submission's form collection dropdown 

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#373] opened 2019-03-21 11:06 UTC
In the submission's form the collection dropdown list only show the 20 (the first page) of communities, and for each community the first 20 collections. So, that as it is now, you can't submit to a collection that isn't on that first page.

[Here](https://github.com/DSpace/dspace-angular/pull/279#discussion_r263826106) a comment with a possible solution, until a properly REST endpoint is implemented

**Comment by tdonohue** [comment] 2020-04-29 20:18
Seems related to or duplicate of #487

**Comment by tdonohue** [comment] 2020-06-26 19:40
Closing, as this was fixed by https://github.com/DSpace/dspace-angular/pull/708

**Closed by tdonohue** 2020-06-26 19:40 UTC
Labels: bug, component: submission, performance / caching
