### ISSUE TITLE
[Accessibility] Combine Adjacent Links

### ISSUE THREAD

**Issue by hostle83** [DSpace/dspace-angular#3082] opened 2024-05-29 11:41 UTC
**Describe the bug**
When adjacent links go to the same location (such as a linked thumbnail image and an adjacent link in a teaser) this results in additional navigation and repetition for keyboard and screen reader users. See WCAG 2 Success Criterion: 2.4.4 Link Purpose (In Context) (https://www.w3.org/TR/WCAG22/#link-purpose-in-context) 

**To Reproduce**
1. On https://sandbox.dspace.org/home or demo.dspace.org/home, items are displayed according to the following structure: thumbnail on the left, teaser text on the right
2. When the thumbnail and the teaser go to the same link, this results in additional navigation and repetition for keyboard and screen reader users.

**Expected behavior**
This can be fixed in multiple ways - making 1 link around the entirety of the result instead of 2 adjacent would work best. Then the thumbnails could have an alt text of alt="" 

**Related work**
https://github.com/DSpace/dspace-angular/issues/1306

**Comment by artlowel** [comment] 2024-08-22 09:53
>making 1 link around the entirety of the result instead of 2 adjacent would work best. Then the thumbnails could have an alt text of alt=""

That way, the link would have to also include the abstract, and you could no longer expand/collapse the abstract by clicking it

**Comment by hostle83** [comment] 2024-09-11 18:37
> is this probably a duplicate of #3070 ?

Yes it looks like it is.

**Comment by tdonohue** [comment] 2024-09-11 21:39
Closing as a duplicate of #3070

**Closed by tdonohue** 2024-09-11 21:39 UTC
Labels: bug, duplicate, help wanted, accessibility, component: Discovery
