### ISSUE TITLE
Multi language support for collection/community fields (title, description, etc)

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1464] opened 2021-12-19 19:02 UTC
It would be very useful to support collection/community fields input and display in different languages.
Option to change UI language is not enough to call DSpace multi-lingual, as only the labels change, the titles remain in one fixed language.

**Comment by tdonohue** [comment] 2023-03-09 22:21
Closing as work on this has moved over to #2056 .  So, this is a duplicate of that more active ticket.

**Closed by tdonohue** 2023-03-09 22:21 UTC
Labels: help wanted, i18n / l10n, new feature, component: Community, component: Collection
