### ISSUE TITLE
During submission some Repeatable fields stop working after a few inserts

### ISSUE THREAD

**Issue by alemarte** [DSpace/dspace-angular#948] opened 2020-11-19 10:47 UTC
**Describe the bug**

When the user stress a repeatable field by adding a few values the UI breaks and new inserted values may be not added to the array. This behaviour has been experienced with Author, Other Title and Seriers/Report NO. of the submission form.

**To Reproduce**
1. Login as admin
2. Start a submission in collection Books
3. Insert an alternative title (aaa) and click +
4. Click Save
5. Insert a second alternative title (bbb) and click +
6. Insert a third alternative title (ccc) and click +

![error1](https://user-images.githubusercontent.com/63857/99654726-08070380-2a5b-11eb-9d02-81f7e7d4a515.png)

The repeatable field is broken and a javascript error occurs.

![error2](https://user-images.githubusercontent.com/63857/99654738-0c332100-2a5b-11eb-84ee-ef491b045512.png)

**Expected behavior**
The added value should appear in the new row, and the template row should reset.

**Comment by tdonohue** [comment] 2021-01-21 19:54
As discussed in today's meeting, we expect this bug will be fixed by the (in progress) fix for #971. Therefore, I'm adding a **0hr** estimate to this bug. If we later find it is not fixed, then we can reanalyze at that time.

**Comment by tdonohue** [comment] 2021-02-23 20:28
This appears to be fixed by #1025 (at least I cannot reproduce it with that PR applied)

**Closed** 2021-04-01 18:53 UTC
Labels: bug, component: submission, e/0
