### ISSUE TITLE
DSpace 7.4 Index-Discovery Problem

### ISSUE THREAD

**Issue by unibravo** [DSpace/dspace-angular#1958] opened 2022-11-07 19:49 UTC
**Describe the bug**
dspace index-discovery -b

Result:
Error from server at http://localhost:8983/solr/search: ERROR: [doc=Item-06ce61a3-62d6-4964-a612-737f5cbe2c3a] Error adding field 'dspace.entity.type'='[Publication, Publication]' msg=Multiple values encountered for non multiValued copy field search.entitytype: Publication

Workaround:
Adding multiValued="true" at following  file:
solr/server/solr/configsets/search/conf/schema.xml
<field name="search.entitytype" type="string" indexed="true" stored="true" required="false"  />

solr/bin/solr stop -all
dspace index-discovery -b

**To Reproduce**
1. Upgraded DSpace 6.4 to 7.3 and after to 7.4 
2. cp -R [dspace]/solr/* [solr]/server/solr/configsets
3. dspace index-discovery -b

**Expected behavior**

**Related work**

dspace@openaccess:$ /dspace/server/bin/dspace index-discovery -b
The script has started
(Re)building index from scratch.
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: **Error from server at http://localhost:8983/solr/search: ERROR: [doc=Item-06ce61a3-62d6-4964-a612-737f5cbe2c3a] Error adding field 'dspace.entity.type'='[Publication, Publication]' msg=Multiple values encountered for non multiValued copy field search.entitytype: Publication**
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:681)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:266)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:248)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:214)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:177)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:138)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:156)
	at org.dspace.discovery.indexobject.IndexFactoryImpl.writeDocument(IndexFactoryImpl.java:147)
	at org.dspace.discovery.indexobject.ItemIndexFactoryImpl.writeDocument(ItemIndexFactoryImpl.java:713)
	at org.dspace.discovery.indexobject.ItemIndexFactoryImpl.writeDocument(ItemIndexFactoryImpl.java:76)
	at org.dspace.discovery.SolrServiceImpl.update(SolrServiceImpl.java:166)
	at org.dspace.discovery.SolrServiceImpl.indexContent(SolrServiceImpl.java:155)
	at org.dspace.discovery.SolrServiceImpl.updateIndex(SolrServiceImpl.java:340)
	at org.dspace.discovery.SolrServiceImpl.updateIndex(SolrServiceImpl.java:327)
	at org.dspace.discovery.SolrServiceImpl.createIndex(SolrServiceImpl.java:295)
	at org.dspace.discovery.IndexClient.internalRun(IndexClient.java:72)
	at org.dspace.scripts.DSpaceRunnable.run(DSpaceRunnable.java:104)
	at org.dspace.app.launcher.ScriptLauncher.executeScript(ScriptLauncher.java:149)
	at org.dspace.app.launcher.ScriptLauncher.handleScript(ScriptLauncher.java:131)
	at org.dspace.app.launcher.ScriptLauncher.main(ScriptLauncher.java:98)
dspace@openaccess:$

**Comment by tdonohue** [comment] 2022-11-07 20:16
@unibravo : That error makes it sound like you have `dspace.entity.type=Publication` two times (duplicated) in the same Item.  You may want to double check the metadata fields for that item (UUID= 06ce61a3-62d6-4964-a612-737f5cbe2c3a), as this error sounds like it's related to your local data.

I'm also not able to reproduce this issue locally when I run `index-discovery -b`.  So, I suspect this is not a bug, and it is a problem with your local data.

If you need more help, please feel free to use one of our recommended Support options: https://wiki.lyrasis.org/display/DSPACE/Support

**Comment by unibravo** [comment] 2022-11-07 21:08
Adding multiValued="true" at following file:
solr/server/solr/configsets/search/conf/schema.xml
solr/bin/solr stop -all
dspace index-discovery -b

**Comment by tdonohue** [comment] 2022-11-07 22:04
@unibravo : I'm not sure I understand your last comment...and whether that's the cause of the error, or the fix?

I do not recommend changing the DSpace Solr schema to `multiValued=true` for that field, as that's unsupported behavior in DSpace at this time.  As far as I'm aware, I think the `dc.entity.type` field is expected to have a *single value*...as that stores the Entity Type, and no object can have multiple Entity Types at the same time.

**Comment by tdonohue** [comment] 2023-03-08 21:57
Closing, this was answered above.

**Closed by tdonohue** 2023-03-08 21:57 UTC
Labels: bug, cannot reproduce, needs triage
