### ISSUE TITLE
Pages are loading twice

### ISSUE THREAD

**Issue by davidatmire** [DSpace/dspace-angular#1357] opened 2021-10-14 09:19 UTC
**Describe the bug**
When you open some DSpace 7 pages, they appear to load twice, which is confusing for the user.

I have been able to reproduce this at least on homepage / collection page / item page even if it doesn't happen systematically.
This behaviour can be experienced on demo7 : https://demo7.dspace.org/home

**To Reproduce**
1. Open https://demo7.dspace.org/home (or other collection / item pages) in a new browser tab
2. The page is first displayed for a short time
3. Then a blank page appears for a short time too
4. Finally the page reappears and is displayed properly

**Expected behavior**
Pages should only be loading once

**Related work**
@artlowel has already identified that 
- the first page displayed is the server side rendered version
- then JS kicks in and it starts loading
- then you see the client side rendered version

**Comment by MarisArins** [comment] 2021-10-14 13:56
I have not seen it in particular, but can this be somehow caused by UI language change ? That is causing UI reload.

**Comment by tdonohue** [comment] 2021-11-03 14:33
@davidatmire and @artlowel : I've seen this behavior. I admit, I had assumed this was somewhat "expected" on the first page load, because the page starts as server-side rendered and then is re-rendered by the client.  That said, I'd love to see this fixed. Is there a recommendation/suggestion for how this would be fixed?

For now, moving to 7.2 board with `high priority` and estimate TBD. 

(@MarisArins : This happens on first page load (first time visiting the site in your browser), and is definitely not caused by a UI language change.  The UI language change does result in a similar reload and it may be impacted by this same issue noted in this ticket.)

**Comment by tdonohue** [comment] 2021-11-08 15:06
Duplicated (with video demo) in #1391

**Comment by tdonohue** [comment] 2021-11-10 17:53
@artlowel : Per today's meeting discussion, assigning this to you / your team & adding your 4hr estimate.  Feel free to start implementation

**Comment by tdonohue** [comment] 2021-11-10 18:05
Corrected estimate to 30hrs.  I mixed this up with a different ticket.

**Closed as completed** 2022-05-19 13:55 UTC
Labels: bug, high priority, performance / caching, e/30
