### ISSUE TITLE
Twice "dspace.entity.type" has been created

### ISSUE THREAD

**Issue by SrinivasRao17** [DSpace/dspace-angular#1571] opened 2022-03-21 16:07 UTC
**After Importing Glossary into DSpace we see multiple dspace.entity.type created in the DSpace 7.1 when we check in "Full Item Page" 

One dspace.entity.type will be blank
second dspace.entity.type will be filled with Metric

Please help us out with this issue. Thanks!!**

A clear and concise description of what the bug is. Include the version(s) of DSpace where you've seen this problem & what *web browser* you were using. Link to ex
![Entity](https://user-images.githubusercontent.com/101823122/159302350-9f91936b-9d74-4d97-865e-cd4765040d25.JPG)
amples if they are public.

**To Reproduce**
1. Do this
2. Then this...

**Expected behavior**

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment] 2022-03-21 16:38
Ah, here's the issue I was thinking about: #1481 ... that issue was related to finding empty `dspace.entity.type` values in 7.1.  It was fixed in 7.2.  It's possible this issue is a duplicate of that one.  If so, then upgrading to 7.2 will fix the problem you are seeing.

**Comment by SrinivasRao17** [comment] 2022-04-08 12:41
Thanks for the update. As mentioned above we will try to upgrade our DSpace

**Closed** 2022-04-08 12:41 UTC
Labels: bug, needs triage
