### ISSUE TITLE
Edit group not implemented

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#911] opened 2020-10-20 09:40 UTC
When trying to chenge group name, there is a message : TODO implement edit Group...

![image](https://user-images.githubusercontent.com/2697696/96569065-5779d880-12d1-11eb-8443-96a19a694585.png)

**Comment by artlowel** [comment] 2020-10-20 09:41
Closing duplicate of #893

**Comment by artlowel** [comment] 2020-10-20 10:01
Apologies, #893 is about delete group, not edit group. Reopening

**Comment by tdonohue** [comment] 2020-10-20 14:10
@artlowel : Could/should this be completed alongside #893, if we bump up the total estimate slightly?

**Comment by artlowel** [comment] 2020-10-20 14:20
It seems this is _actually_ not implemented. So it's not just removing the notification in this case. So I'd add **2 hours**, and we'll include it in the PR for #893

**Comment by tdonohue** [comment] 2020-10-28 14:26
As noted in Slack, this is an accidental duplicate of #836.

**Comment by tdonohue** [comment] 2020-11-12 17:46
Updated estimate per https://github.com/DSpace/dspace-angular/pull/925#issuecomment-726232636

**Closed** 2020-12-03 21:59 UTC
Labels: bug, e/3
