### ISSUE TITLE
User profile menu remains open after menu entry is selected

### ISSUE THREAD

**Issue by eligit22** [DSpace/dspace-angular#3021] opened 2024-05-08 16:02 UTC
**Describe the bug**
After logging in DSpace v.8, after opening the user profile menu to select one of the available entry to browse to, for instance, the MyDSpace or the Profile page, the menu doesn't close automatically after the click, and it remains open also after landing on the chosen page

**To Reproduce**
1. Log in to DSpace
2. Open the user profile menu
3. Select "MyDSpace"

**Expected behavior**
After logging in, I open the user profile menu to select one of the available entry to browse to ( for instance, "MyDSpace"), and the menu closes automatically after the click while landing on the chosen page

**Related work**
Link to any related tickets or PRs here.

https://github.com/DSpace/DSpace/assets/122300428/90467a96-da98-40e7-aebe-e5f8e15e2677

**Comment by alanorth** [comment] 2024-05-09 06:30
Thanks @eligit22. I'm moving this issue to the dspace-angular issue tracker, since it is a frontend bug.

Regarding the bug itself, I've seen "sticky" menus from the main navbar dropdowns as well, though I don't know how to reproduce it. It happens to me periodically when using our DSpace 7.6.1 repository.

**Comment by atarix83** [comment] 2024-07-01 15:04
@tdonohue @hostle83

4science is interested in working on this task and the related one https://github.com/DSpace/dspace-angular/issues/3085

Estimation is about 6h

**Closed** 2024-12-18 18:08 UTC
Labels: bug, accessibility, e/6, claimed: 4Science, funded
