### ISSUE TITLE
Internationalization issues

### ISSUE THREAD

**Issue by benbosman** [DSpace/dspace-angular#870] opened 2020-09-21 15:11 UTC
**Describe the bug**
We noticed that new features not added to alternative languages display message keys

**To Reproduce**
1. Open https://dspace7-demo.atmire.com/admin/curation-tasks with your browser language set to English: it looks good
2. Open the same page using a different browser language (I tested with Dutch), it looks like https://www.dropbox.com/s/7uxuiu446sf4j1f/Schermafbeelding%202020-09-21%20om%2011.48.16.png?dl=1

**Expected behavior**
It should display the messages in the default language

**Comment by tdonohue** [comment] 2020-09-24 16:21
I'm seeing a slightly different behavior (though it is still broken as @benbosman notes):
1. Login to  https://dspace7-demo.atmire.com/
2. Open https://dspace7-demo.atmire.com/admin/curation-tasks (looks good)
3. Use the globe to change languages...I'm redirected back to the homepage (https://dspace7-demo.atmire.com/), but the new language is shown.
4. If I browse back to https://dspace7-demo.atmire.com/admin/curation-tasks then that page is shown in the new language.

So, I think this is a bug, but the improper behavior that I saw was that I was now redirected back to the homepage after changing language.  Scheduling for beta 5.

**Comment by benbosman** [comment] 2020-09-25 08:49
@tdonohue that seems to be a different bug actually
My test was not based on the globe button, but based on default browser languages
You can simulate it using https://chrome.google.com/webstore/detail/locale-switcher/kngfjpghaokedippaapkfihdlmmlafcc to avoid changing your browser to a language you don't understand :)

**Comment by atarix83** [comment] 2020-10-22 13:04
I can't reproduce the error reported by @benbosman even if i use the linked chrome extension.
estimation date to redirect to the previous page after language switch is about 1 hour

**Comment by tdonohue** [comment] 2020-10-22 19:57
Thanks for the analysis here, @atarix83 .  Your estimate of **1hr** to fix the redirect seems fine to me.

**Comment by tdonohue** [comment] 2021-02-18 15:08
May already be solved. Just needs testing

**Comment by tdonohue** [comment] 2021-02-23 17:28
Closing, as this issue is fixed.  However, the separate issue described in [my initial comment above](https://github.com/DSpace/dspace-angular/issues/870#issuecomment-698448436) is not yet resolved, so I've moved that into #1030

**Closed by tdonohue** 2021-02-23 17:28 UTC
Labels: bug, e/1, i18n / l10n
