### ISSUE TITLE
There needs to be a field to add alt text for logos when adding collections

### ISSUE THREAD

**Issue by LTGtang** [DSpace/dspace-angular#3237] opened 2024-08-07 15:50 UTC
## Describe the bug
In the staff interface, when creating a new collection, there is a place to upload a logo. There is not a field to add alt text for the logo.
![Screenshot 2024-08-07 at 11 47 05 AM](https://github.com/user-attachments/assets/6f9ae7d4-af92-4841-8f6e-e95371d1ede6)

## To Reproduce
1. log in to DSpace.
2. Click on Create new... collection
3. See that there isn't a field for adding the alt text for the logo

## Expected behavior
There needs to be a field for adding the alt text. Perhaps it might be possible to add an AI widget of some sort to do a baseline (with all faults) of description or at least add the filename of the uploaded file as alt text (also not ideal) but by having this field and making sure it's populated, it will resolved some accessibility testing issues in the future.

## Related work
lots of accessibility tickets

**Comment by LTGtang** [comment] 2024-08-07 16:05
Ah, apologies, this might be a duplicate of this ticket https://github.com/DSpace/dspace-angular/issues/1306

**Comment by tdonohue** [comment] 2024-08-07 19:25
@LTGtang : No worries. You are correct though... this is a duplicate of #1306.  Closing this ticket as a duplicate because #1306 is already being worked on (see comments on that ticket).

**Closed by tdonohue** 2024-08-07 19:25 UTC
Labels: bug, needs triage
