### ISSUE TITLE
URI link on simple item page always opens in a new page/tab

### ISSUE THREAD

**Issue by saiful-semantic** [DSpace/dspace-angular#3241] opened 2024-08-08 11:54 UTC
## Describe the bug
In DSpace 8.0, the URI link on item page always opens in a new page.

## To Reproduce
1. Deploy DSpace Angular UI on a reverse proxy setup with FQDN
2. Then open any item page page. e.g. https://demo.dspace.org/items/f1e9085d-048c-4203-b769-b7350f56c7a3
3. Click on the URI. e.g.: https://demo.dspace.org/handle/10673/1431
It will open a new page despite the item being within the same domain.

## Expected behavior
Ideally links belonging to the same FQDN should open within the same page.

## Related work
On digging further I think the reason is _hasInternalLink_ function.

In lines 134-136 of `src/app/item-page/field-components/metadata-values/metadata-values.component.ts`:

```
hasInternalLink(linkValue: string): boolean {
   return linkValue.startsWith(environment.ui.baseUrl);
}
```
When we use a reverse proxy for the UI (as in most production deployments), this function always returns a `false` value. e.g.,
`environment.ui.baseUrl = http://localhost:4000`
`linkValue = https://production-domain/handle/x/xx [assuming the fake handle]`

This makes each URI in simple item page opening in a new window/tab.

**Comment by Andrea-Guevara** [comment] 2024-08-28 19:57
Good afternoon @tdonohue! My name is Andrea and I'm part of Neki-it. We want to do this activity.

**Comment by tdonohue** [comment] 2024-09-03 21:55
Thanks @Andrea-Guevara .  I'll assign this to you for your team. Please let us know on this ticket if you need advice on any solution you may be working on.

**Comment by Andrea-Guevara** [comment] 2024-09-05 15:33
Good afternoon @tdonohue! I was able to reproduce this error a few days ago, but now I can't reproduce the error on https://demo.dspace.org which is on version 8.

I was wondering if this is still a problem?

**Comment by saiful-semantic** [comment] 2024-09-06 06:38
> I was wondering if this is still a problem?

Yes it still is. Try clicking on the URI in this page:
https://demo.dspace.org/entities/publication/397b2902-a889-4ba1-939f-c9a4c3a7d814

**Comment by Andrea-Guevara** [comment] 2024-09-12 11:56
Good morning @saiful-semantic, I hope you're well!

We have provided a PR as a possible solution to this problem. If necessary, we welcome suggestions for improving the code.

We look forward to your feedback!

**Closed** 2024-12-19 17:44 UTC
Labels: bug, component: Item, affects: 8.x
