### ISSUE TITLE
Permanent uri link of Communities, Collections is malformed 

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/dspace-angular#887] opened 2020-10-08 07:31 UTC
**Describe the bug**
On DSpace 7 the permanent uri of Communities and Collections is malformed, having http://localhost:3000 as domain instead of actual one. 
See, as example https://dspace7-demo.atmire.com/collections/dd1240ae-d7dd-405c-bdc3-
(https://user-images.githubusercontent.com/70699836/95428261-15ec4380-0949-11eb-9874-f739039f167b.png)
d6c960609433 . 

![Screenshot from 2020-10-08 09-31-21](https://user-images.githubusercontent.com/70699836/95428403-416f2e00-0949-11eb-8315-4fd3b4e0cff8.png)

**To Reproduce**
1. Navigate to a community or collection page of DSpace 7

**Expected behavior**
A permanent URI link not pointing to a local or malformed domain. 
I think we can evaluate how this link has to be built, there can be two options: create the url at angular side, using for example, current installation domain. Otherwise we can use the dc.​identifier.​uri metadata as already done with Items, in this case it should be possible to deal with external links (hdl) as permanent URI of Communities and Collections.

**Related work**
https://github.com/DSpace/dspace-angular/issues/886

**Comment by corrad82-4s** [comment] 2020-10-12 17:30
We (4Science) believe that a good solution might be working on rest part and generate dc.identifier.uri for Communities and Collections as already done for Items. 
If you agree, we can take in charge this development. We estimate to develop this solution, including a Flyway script that would set this metadata for existing Communities and Collections in a working day, for the whole rest part. 

In addition to this, we can take in charge angular part as well. We estimate that such front-end development would take 2 hours of work.

**Comment by tdonohue** [comment] 2020-10-15 17:48
This ticket is a duplicate of #657.... however, it better describes the issue & options, so I'll close #657 and link to this ticket.

I'm OK with the approach of storing Community/Collection URIs in the `dc.identifier.uri` field similar to Items.  That retains consistency across DSpaceObjects.

I'll update this ticket with an estimate for the full **10 hours** (8hours backend, 2hours frontend) as both tasks should be performed by the same team.   @corrad82-4s , I'll assign this to you, but you are free to reassign internally.

**Closed** 2020-11-23 15:21 UTC
Labels: bug, component: Collection, component: Community, e/10, identifiers: Handles
