### ISSUE TITLE
When using entities, metadata values with visibility set as “workflow” are not displayed in the UI during workflow.

### ISSUE THREAD

**Issue by pilasou** [DSpace/dspace-angular#1822] opened 2022-09-13 19:43 UTC
**Describe the bug**
During workflow, after selecting an entity in a metadata (i.e dc.contributor.author) the value is not  displayed in the UI but the relation is effectivelly created. 

If the page is refreshed manually, the entity is displayed.  

This problem occurs if the metadata element on which the entity is configured in the submission-forms.xml with the visibility status “workflow” (as shown below). 
![image](https://user-images.githubusercontent.com/19291880/189993812-ce8efc85-6e4a-415b-b068-b6686883c0ed.png)

**To Reproduce**

1. Assign <visibility>workflow</visibility> to a metadata field (i.e dc.contributor.author). 
2. Log in as submitter and go to MyDSpace. 
3. Make a new submission in the collection in with previously metadata field has been configured. 
4. Log in as editor and go to MyDSpace and display workflow tasks. 
5. Assign yourself the newly made submission. 
![image](https://user-images.githubusercontent.com/19291880/189993922-2c0fa511-c1a0-4e79-a988-71c556c9276e.png)
6. On the metadata field clic on the magnifying glass buton.  
7. Select at least one value in the window and close the window. 

![image](https://user-images.githubusercontent.com/19291880/189994295-1ff9b334-cc28-4af7-9cfc-7b5947dfe308.png)

The values selected are not displayed on the page. 

Refresh the page, the values are displayed. 

**Expected behavior**
Trigger an automatic refresh of the form when value have been selected in the entity search page so that it is displayed. 
 
**Related work**
This problem may have been caused by the following patch introduced in 7.3: https://github.com/DSpace/dspace-angular/pull/1524

**Comment by FelixNicol** [comment] 2022-09-14 18:01
This is a patch for this problem in section-form.component.ts:

`  /**
   * Whether a specific field is editable in the current scope. Unscoped fields always return true.
   * @private
   */
  private inCurrentSubmissionScope(field: string): boolean {
    const scope = this.formConfig?.rows.find(row => {
      return row.fields?.[0]?.selectableMetadata?.[0]?.metadata === field;
    }).fields?.[0]?.scope;
 
    switch (scope) {
      case SubmissionScopeType.WorkspaceItem: {
        **return (this.submissionObject as any).type === WorkspaceItem.type.value;**
      }
      case SubmissionScopeType.WorkflowItem: {
        **return (this.submissionObject as any).type === WorkflowItem.type.value;**
      }
      default: {
        return true;
      }
    }
  }`

Currently the two strict equality comparisions always return false. The patch allow proper comparision between values. 

There are similar patches using boxing elsewere in the code. I think this is caused by the deserialisation of the response by angular which type submissionObject.type as string instead of an instance of the class «ResourceType». Casting submissionObject allow us to compare the strings. 

A more robust solution would likely be to adjust how angular deserialise the response into a submissionObject. However it would also require some changes everywere similar patches where applied.

**Comment by FelixNicol** [comment] 2022-09-14 19:04
section-form.component.spec.ts will also require the folowing change to reproduce this behavior: 

<img width="373" alt="image" src="https://user-images.githubusercontent.com/98552762/190240813-1b849ecd-2d7e-4e12-95c2-dd7381014f4d.png">

**Comment by tdonohue** [comment] 2022-09-14 19:49
@FelixNicol : Would you be able to send us these fixes as a [Pull Request (PR)](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)?  That'd make it much easier for me to assign it to someone else to review/test (and possibly get it into the next release).  Otherwise, I'll have to look for a developer who can turn your notes above into a PR.

**Comment by FelixNicol** [comment] 2022-09-14 19:51
@tdonohue I will do that tomorrow.

**Closed** 2022-10-03 22:15 UTC
Labels: bug, component: configurable entities, component: workflow, needs triage
