### ISSUE TITLE
Usability issue in Embargo's section at submission

### ISSUE THREAD

**Issue by paulo-graca** [DSpace/dspace-angular#1382] opened 2021-10-28 13:48 UTC
**Describe the bug**
There is an usability issue regarding file embargo features, that if you don't know, you will lose data because you didn't save that section of the submission form. And it's very easy to miss that save option.

**To Reproduce**
- start submission and upload any file
- at upload section, if you click the edit option you will have a form
- you can make changes and set an embargo, and if you slightly scroll the page, the save section option will vanish from your field of view
![image](https://user-images.githubusercontent.com/877488/139266885-b2a11835-ea79-4c0b-acbd-7c870804eea5.png)
- you will assume the form will autosave, but no. If you don't push the save (green disk) at the upper part of your screen, you will lose data.

**Expected behavior**
If you fill data in a form as you write in paper, you will fill from top to bottom, left to right. So it makes sense to have the save option at the end of the form (bottom right side). I suggest to move those options there and consider using buttons (Glyphicons) with captions instead of that large icons.

**Comment by tdonohue** [comment] 2021-11-10 17:17
Closing in favor of #1399 which proposes solving this problem via a new popup modal, to be implemented as part of the 7.2 release.  So, this issue is a duplicate of #1399....and I'm moving this work over to #1399 as that ticket describes the proposed solution.

**Closed by tdonohue** 2021-11-10 17:17 UTC
Labels: bug, usability, component: submission
