### ISSUE TITLE
Export/import options missing from admin menu after shibboleth login

### ISSUE THREAD

**Issue by mspalti** [DSpace/dspace-angular#1953] opened 2022-11-04 21:44 UTC
**Describe the bug**
The admin menu is shown after logging via Shibboleth as an administrator (fixed by https://github.com/DSpace/dspace-angular/pull/1805) However, the export and import options are missing from the menu.   To see these options, you need to reload the page.

**To Reproduce**
1. Login via shibboleth as admin
2. Export / Import options will be missing
3. Reload the page and the options appear

**Related work**
 https://github.com/DSpace/dspace-angular/pull/1805

**Comment by tdonohue** [comment] 2022-12-13 15:21
@ybnd : Wanted to ping you on this as this bug seems to be a follow-up to #1805, which you fixed.  If it's something you are interest in, let me know.  It'd obviously be nice to get this menu working properly for Shibboleth auth.

**Comment by tdonohue** [comment] 2023-06-29 20:17
Should be retested in 7.6.  Is it possible that https://github.com/DSpace/dspace-angular/pull/2187 could have fixed this (or improved it?).

**Comment by mspalti** [comment] 2023-06-29 23:48
This seems to be working on our site now. I'm not running 7.6 yet, but the #2187 fix is applied to our site so that might have fixed it.

**Comment by tdonohue** [comment] 2023-06-30 14:25
Thanks for the verification @mspalti ... I suspected this error was a side effect of the larger problem fixed by #2187.

In that case, I'm going to close this as "fixed" in 7.6.  If we find it's not fully resolved we can always reopen it later on.

**Comment by pybrarian** [comment] 2024-01-30 22:53
I just want to note that in our development server, this is still happening after the upgrade to 7.6.1. All other menu options show on first Shibboleth login, but Import and Export menus do not show until a manual page refresh.

I will update once we move 7.6.1 to production in the next week or so, but our dev environment is very close to our production one so I don't expect a difference.

**Comment by nwoodward** [comment] 2024-02-15 17:15
Chiming in here to say that like @pybrarian this is still a problem for one of our administrator users after they log in with Shibboleth. We're on version 7.6.1. The import/export menu options don't appear after they log in until they refresh or click around on the page at least once. I'm going to video chat with them to see if there's any information in the browser's dev tools.

**Comment by tdonohue** [comment] 2024-02-15 17:18
Reopening as it seems this may not be solved completely by #2187.  Moving it back to the 7.6.x project, but it is waiting on a volunteer.

**Comment by mspalti** [comment] 2024-02-16 18:33
We see the same problem. I think it stopped working in 7.6.1, for reasons possibly related to #2669. A fix for that issue is in 7.6.2 but I haven't tested to see if it also resolves the menu issues.

**Comment by tdonohue** [comment] 2024-02-16 19:25
Could someone watching this ticket test to see if #2670 fixes this bug?  That's the code that was added to (unreleased) 7.6.2 in order to fix #2669.  If that solves the problem, then this ticket would be essentially a "duplicate" of #2669 & can be closed again.

**Comment by abbydrury** [comment] 2024-02-23 18:54
> Could someone watching this ticket test to see if #2670 fixes this bug? That's the code that was added to (unreleased) 7.6.2 in order to fix #2669. If that solves the problem, then this ticket would be essentially a "duplicate" of #2669 & can be closed again.

Running 7.6.1 with this patch in our test environment – it fixed #2669 but **not** this issue (#1953).

**Comment by nwoodward** [comment] 2024-02-27 21:51
Same here. I pulled #2670 into the codebase, but this problem persists.

**Comment by nwoodward** [comment] 2024-03-06 18:49
This has become a showstopper for us, and I'm trying to figure out if 1) we need to revert back to 7.6, 2) there's a workaround, 3) there's a particular commit that I can revert for now, or 4) anyone has any ideas about where the problem is. I'm willing to attempt a solution, but a clue or two would help.

It's to the point for some Shibboleth users where no amount of refreshing or clicking around brings the import/export menus back.

**Comment by tdonohue** [comment] 2024-03-06 19:23
@nwoodward : It's unclear to me where the issue resides and how it *began again* between 7.6 and 7.6.1.   So, I don't have any great advice right now.  This really needs closer analysis & I've had difficulty finding anyone willing to volunteer.

My only recommendation would be to first test with latest `dspace-7_x` branch to see if it's somehow magically "fixed" in pre-7.6.2.  If not (and it likely isn't), then perhaps a "clue" would be to see if you can determine what may have broken it between 7.6 and 7.6.1. I wish I had better advice.  But, maybe someone else will chime in with additional clues.

**Comment by nwoodward** [comment] 2024-03-11 17:54
Hi @tdonohue. Thanks for the information. I'll look around at the commit history.

**Comment by mspalti** [comment] 2024-03-12 23:36
@tdonohue on a side note, I tried to set up a Shibboleth test environment using [the docker image](https://github.com/DSpace/DSpace/blob/main/dspace/src/main/docker-compose/README.md). But it looks like https://samltest.id/ is no longer available. I tried a two other potential test Idp services but I wasn't able to get either of them working.

**Closed** 2024-09-05 20:54 UTC
Labels: bug, help wanted, high priority, authentication: Shibboleth, performance / caching
