### ISSUE TITLE
Can't create new policy for a bitstream

### ISSUE THREAD

**Issue by gsteinhart** [DSpace/dspace-angular#1141] opened 2021-04-30 19:26 UTC
To reproduce the issue, logged in as admin:

1. Find or create an item with bitstreams
2. Edit item
3. Choose Status > Authorizations
4. (Can't keep doing the steps to document here, now, because demo instance is hung up and I can't access my item, but here are the errors messages: "An error occurred while creating resource policy" and ""Unprocessable or invalid entry")

**Comment by tdonohue** [comment] 2021-05-03 18:51
@gsteinhart : I tried this today, and it's working for me on the demo site (and locally).  So, I wonder if this was a temporary issue (perhaps caused by deleted data last week).  Here's what I see:

1. Login as an admin (dspacedemo+admin@gmail.com)
2. Browse/search for an Item which has a Bitstream
3. Click Edit on the Item
4. On the "Status" tab, click "Authorizations"
5. Under "Bitstream" policies click "Add" and create a new "Resource Policy" (minimally select a Policy type like "Custom" and an Action type, e.g. "Read" and person/group).

It is worth noting that you can *only add Bitstream resource policies if a Bitstream exists*.  So, make sure you edit an Item that has one or more Bitstreams.

If I overlooked something, let me know. But, it looks to me like this is working fine, so it might have just been a brief hiccup.

**Comment by tdonohue** [comment] 2021-05-26 14:55
Closing, as this has been unreproducible. If it's able to be reproduced at a later date, we can reopen with additional information.

**Closed by tdonohue** 2021-05-26 14:55 UTC
Labels: cannot reproduce, testathon
