### ISSUE TITLE
Add Recently Added section to Home and Community pages and make number of items configurable

### ISSUE THREAD

**Issue by alawvt** [DSpace/dspace-angular#1775] opened 2022-08-17 21:53 UTC
**Is your feature request related to a problem? Please describe.**
In DSpace 7, Recently Added items (which are not labeled as such, only "Browse") appear only in Collection pages, not the Home or Community pages. Initially there are 5 items displayed. Clicking on the page links takes one to the next page of 5 items.
<img width="603" alt="DSpace7_recently_added" src="https://user-images.githubusercontent.com/13037168/185249068-7ff2998c-038d-4f2d-b738-b6e112e96d4c.png">

**Describe the solution you'd like**
In DSpace 6 XMLUI, Recently Added items display on the Home page, Community, and Collection pages. Initially there are a configurable number of items in the section, (recentSubmissionConfiguration, https://wiki.lyrasis.org/display/DSDOC6x/Discovery#Discovery-CustomizingtheRecentSubmissionsdisplay). Clicking on the arrows takes one to a page with the next 20 items. 
<img width="1097" alt="DSpace6_XMLUI_recently_added" src="https://user-images.githubusercontent.com/13037168/185249054-4a2f564c-8704-45ab-a9a7-929a3c2cc983.png">

One idea is to implement this section as a Browse by reverse submit or accession date. Provide a configuration of how many items to include in the initial display. On succeeding pages of results, include the same user configuration that appears on the browse by pages. This will allow the user to set how many items to display.
<img width="1208" alt="DSpace6_XMLUI_browse_reverse_submit_date" src="https://user-images.githubusercontent.com/13037168/185250473-57d25597-a7c4-4da9-890e-5e879649cd87.png">

**Describe alternatives or workarounds you've considered**

**Additional context**

**Comment by tdonohue** [comment] 2022-08-26 19:42
This appears to be a duplicate of #667 .  Some early work has already begun on this feature by a volunteer, but it's unclear when it'll be ready.  Some screenshot examples are in that other ticket.

I'm closing this ticket as duplicate as discussion should move to the open ticket.

**Closed by tdonohue** 2022-08-26 19:42 UTC
Labels: new feature, needs triage
