### ISSUE TITLE
Running application with defining configuration ui.nameSpace doesn't work

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#1829] opened 2022-09-16 09:08 UTC
**Describe the bug**
With the main branch running application with defining configuration ui.nameSpace doesn't work properly, while is working properly in the 7.3 release. The problem is the dspace-theme.css is not loaded and the result is the following 
![Schermata da 2022-09-16 10-41-39](https://user-images.githubusercontent.com/2486489/190601151-edb2e8d0-6a82-4cd4-95af-7be948c363c6.png)

**To Reproduce**
1. in the config.dev.yml configure a different namespace for the ui, e.g:
``` 
ui:
  ssl: false
  host: localhost
  port: 4000
  nameSpace: /ui
  rateLimiter:
    windowMs: 60000
    max: 500
```
2. run application with yarn start:dev

**Expected behavior**
The page should be loaded properly when a different namespace than `/` is used

**Related work**
this was alredy fixed in the 7.3 release by this PR https://github.com/DSpace/dspace-angular/pull/1642

**Comment by artlowel** [comment] 2022-09-16 09:52
Sounds like it could be a duplicate of https://github.com/DSpace/dspace-angular/issues/1778
@atarix83 can you check whether https://github.com/DSpace/dspace-angular/pull/1814 fixes it?

**Comment by tdonohue** [comment] 2022-09-16 14:31
@atarix83 and @artlowel : this bug appears to **only impact dev mode**.   
* I cannot reproduce it if I run in production mode (`yarn build:prod; yarn serve:ssr`) -- in prod mode the "dspace" theme and everything loads perfectly.  
* But, I can reproduce it if I run `yarn start:dev`.

So, it does sound slightly similar to #1814... but that PR (which is now merged) didn't fix this problem.

I'll pull this over onto our 7.4 board in case anyone wants to dig in further. Since it's not impacting production, I'm going to flag it as `medium priority`, but if we find it's a very simple/quick fix, then I'm OK with including this as paid work for 7.4

**Comment by tdonohue** [comment] 2022-09-16 14:41
@atarix83 and @artlowel :  Ok, I'm mistaken.  It also _partially impacts_ production.  

When running in production mode:
* The homepage looks correct
* If you browse to any other page, the main `dspace-theme.css` fails to load with this error (in Chrome DevTools)
```
Refused to apply style from 'http://localhost:4000/dspace-theme.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```
* If you click reload in the browser, then that same page will appear correctly (although the error is still shown in DevTools regarding the main `dspace-theme.css` file.

Bumping up the priority to `high priority` as this is definitely broken.

**Comment by artlowel** [comment] 2022-09-16 14:42
We'll also take a look at this one

**Comment by tdonohue** [comment] 2022-09-16 14:45
Thanks @artlowel .  Assigning to you then to work on for 7.4

**Closed** 2022-09-23 14:39 UTC
Labels: bug, help wanted, high priority, configuration, themes, Estimate TBD
