### ISSUE TITLE
Metadata export fails sometimes

### ISSUE THREAD

**Issue by santilococo** [DSpace/dspace-angular#2224] opened 2023-05-02 09:57 UTC
**Describe the bug**
Sometimes metadata export fails. I need to run it a few times and then it will work.

```
2023-05-02 05:42:03,920 ERROR unknown unknown org.dspace.storage.bitstore.DSBitStoreService @ put(101454695997340847443849127692011603797, inputstream)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:?]
	at java.io.File.createNewFile(File.java:1035) ~[?:?]
	at org.dspace.storage.bitstore.DSBitStoreService.put(DSBitStoreService.java:103) [dspace-api-7.5.jar:7.5]
	at org.dspace.storage.bitstore.BitstreamStorageServiceImpl.store(BitstreamStorageServiceImpl.java:116) [dspace-api-7.5.jar:7.5]
	at org.dspace.content.BitstreamServiceImpl.create(BitstreamServiceImpl.java:122) [dspace-api-7.5.jar:7.5]
	at org.dspace.scripts.ProcessServiceImpl.appendFile(ProcessServiceImpl.java:165) [dspace-api-7.5.jar:7.5]
	at org.dspace.app.rest.scripts.handler.impl.RestDSpaceRunnableHandler.writeFilestream(RestDSpaceRunnableHandler.java:253) [classes/:7.5]
	at org.dspace.app.bulkedit.MetadataExport.internalRun(MetadataExport.java:67) [dspace-api-7.5.jar:7.5]
	at org.dspace.scripts.DSpaceRunnable.run(DSpaceRunnable.java:104) [dspace-api-7.5.jar:7.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-05-02 05:42:03,921 ERROR unknown unknown org.dspace.app.rest.scripts.handler.impl.RestDSpaceRunnableHandler @ Process id: 17, script name: metadata-export, message: null
java.io.IOException: java.io.IOException: No such file or directory
	at org.dspace.storage.bitstore.DSBitStoreService.put(DSBitStoreService.java:122) ~[dspace-api-7.5.jar:7.5]
	at org.dspace.storage.bitstore.BitstreamStorageServiceImpl.store(BitstreamStorageServiceImpl.java:116) ~[dspace-api-7.5.jar:7.5]
	at org.dspace.content.BitstreamServiceImpl.create(BitstreamServiceImpl.java:122) ~[dspace-api-7.5.jar:7.5]
	at org.dspace.scripts.ProcessServiceImpl.appendFile(ProcessServiceImpl.java:165) ~[dspace-api-7.5.jar:7.5]
	at org.dspace.app.rest.scripts.handler.impl.RestDSpaceRunnableHandler.writeFilestream(RestDSpaceRunnableHandler.java:253) [classes/:7.5]
	at org.dspace.app.bulkedit.MetadataExport.internalRun(MetadataExport.java:67) ~[dspace-api-7.5.jar:7.5]
	at org.dspace.scripts.DSpaceRunnable.run(DSpaceRunnable.java:104) [dspace-api-7.5.jar:7.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:?]
	at java.io.File.createNewFile(File.java:1035) ~[?:?]
	at org.dspace.storage.bitstore.DSBitStoreService.put(DSBitStoreService.java:103) ~[dspace-api-7.5.jar:7.5]
	... 9 more
2023-05-02 05:42:03,922 INFO  unknown unknown org.dspace.scripts.service.ProcessService @ anonymous::process_fail:Process with ID 17 and name metadata-export has failed
2023-05-02 05:42:03,922 ERROR unknown unknown org.dspace.storage.bitstore.DSBitStoreService @ put(29556244549471869094406599202716908621, inputstream)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:?]
	at java.io.File.createNewFile(File.java:1035) ~[?:?]
	at org.dspace.storage.bitstore.DSBitStoreService.put(DSBitStoreService.java:103) [dspace-api-7.5.jar:7.5]
	at org.dspace.storage.bitstore.BitstreamStorageServiceImpl.store(BitstreamStorageServiceImpl.java:116) [dspace-api-7.5.jar:7.5]
	at org.dspace.content.BitstreamServiceImpl.create(BitstreamServiceImpl.java:122) [dspace-api-7.5.jar:7.5]
	at org.dspace.scripts.ProcessServiceImpl.appendFile(ProcessServiceImpl.java:165) [dspace-api-7.5.jar:7.5]
	at org.dspace.scripts.ProcessServiceImpl.createLogBitstream(ProcessServiceImpl.java:303) [dspace-api-7.5.jar:7.5]
	at org.dspace.app.rest.scripts.handler.impl.RestDSpaceRunnableHandler.addLogBitstreamToProcess(RestDSpaceRunnableHandler.java:308) [classes/:7.5]
	at org.dspace.app.rest.scripts.handler.impl.RestDSpaceRunnableHandler.handleException(RestDSpaceRunnableHandler.java:150) [classes/:7.5]
	at org.dspace.app.rest.scripts.handler.impl.RestDSpaceRunnableHandler.handleException(RestDSpaceRunnableHandler.java:133) [classes/:7.5]
	at org.dspace.scripts.DSpaceRunnable.run(DSpaceRunnable.java:107) [dspace-api-7.5.jar:7.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-05-02 05:42:03,922 ERROR unknown unknown org.dspace.app.rest.scripts.handler.impl.RestDSpaceRunnableHandler @ RestDSpaceRunnableHandler with process: 17 could not write log to process
java.io.IOException: java.io.IOException: No such file or directory
	at org.dspace.storage.bitstore.DSBitStoreService.put(DSBitStoreService.java:122) ~[dspace-api-7.5.jar:7.5]
	at org.dspace.storage.bitstore.BitstreamStorageServiceImpl.store(BitstreamStorageServiceImpl.java:116) ~[dspace-api-7.5.jar:7.5]
	at org.dspace.content.BitstreamServiceImpl.create(BitstreamServiceImpl.java:122) ~[dspace-api-7.5.jar:7.5]
	at org.dspace.scripts.ProcessServiceImpl.appendFile(ProcessServiceImpl.java:165) ~[dspace-api-7.5.jar:7.5]
	at org.dspace.scripts.ProcessServiceImpl.createLogBitstream(ProcessServiceImpl.java:303) ~[dspace-api-7.5.jar:7.5]
	at org.dspace.app.rest.scripts.handler.impl.RestDSpaceRunnableHandler.addLogBitstreamToProcess(RestDSpaceRunnableHandler.java:308) [classes/:7.5]
	at org.dspace.app.rest.scripts.handler.impl.RestDSpaceRunnableHandler.handleException(RestDSpaceRunnableHandler.java:150) [classes/:7.5]
	at org.dspace.app.rest.scripts.handler.impl.RestDSpaceRunnableHandler.handleException(RestDSpaceRunnableHandler.java:133) [classes/:7.5]
	at org.dspace.scripts.DSpaceRunnable.run(DSpaceRunnable.java:107) [dspace-api-7.5.jar:7.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:?]
	at java.io.File.createNewFile(File.java:1035) ~[?:?]
	at org.dspace.storage.bitstore.DSBitStoreService.put(DSBitStoreService.java:103) ~[dspace-api-7.5.jar:7.5]
	... 11 more
```

The `metadata-export` script, on the other hand, works perfectly, so I don't know why this is happening.

I don't think this is a permissions related issue because sometimes it works and sometimes it doesn't.

Do you know where DSpace is trying to create a file? Maybe that directory is the problem.

**To Reproduce**
1. Export metadata of a collection from the frontend.

**Other**
- DSpace 7.5

**Comment by tdonohue** [comment] 2023-05-02 14:43
@santilococo : This sounds like there may be a permissions issue in your Assetstore folder (`[dspace]/assetstore/`) or one of the subfolders.  All bitstreams are stored in that folder, and the errors you are showing above seem to imply that sometimes when a bitstream is saved to that folder, it throws an error.

I'm not able to reproduce this & I suspect it's a permissions error. Therefore, I'm closing this ticket.  

If you need more support, please use one of our support options at https://wiki.lyrasis.org/display/DSPACE/Support

**Closed by tdonohue** 2023-05-02 14:43 UTC
Labels: bug, needs triage
