### ISSUE TITLE
Top navbar rendering incorrectly when interacting with item's bitstreams

### ISSUE THREAD

**Issue by Sondissimo** [DSpace/dspace-angular#2429] opened 2023-08-09 15:41 UTC
**Describe the bug**
When we select an item, if we open the bitstream to visualize it, we encounter a strange behaviour regarding the top navbar.
Version: 7.6

**To Reproduce**
1. When we visualize an item bitstream the navbar is not correctly rendering
![image](https://github.com/DSpace/DSpace/assets/119754561/197a490e-3f43-4835-ae41-5b791808ea7c)

**Expected behavior**
The navbar shouldnt be visible when inspecting bitstreams

**Related work**
https://github.com/DSpace/DSpace/issues/9022

**Comment by Sondissimo** [comment] 2023-08-09 15:43
I'll take the task on behalf of 4Science

**Comment by alexandrevryghem** [comment] 2023-08-09 16:59
This is a duplicate of #2341

**Comment by tdonohue** [comment] 2023-08-09 18:44
@Sondissimo : I'm going to close this ticket & move the details to #2341 (as it was already logged as a bug there).  I'll assign you to #2341 though (thanks for volunteering!) as that has no current volunteer.

Closing this as a duplicate.  All future activity/discussion should move to #2341

**Closed by tdonohue** 2023-08-09 18:44 UTC
Labels: bug, needs triage
