### ISSUE TITLE
An error accurs when changing the ORCID synchronization settings

### ISSUE THREAD

**Issue by pilasou** [DSpace/dspace-angular#2999] opened 2024-05-02 18:55 UTC
**Describe the bug**
When trying to change a settings on the ORCID Synchronization setting page, an error is displayed when clicking on Save button: "The update of the synchronization settings failed"

However, the setting is change accordingly.

**To Reproduce**
1. In DSpace Sandbox (https://sandbox.dspace.org/), log in using an  ORCID Sandbox user account.
2. Go to user Profile
3. In Researcher Profile, clic Create New
4. Person Item created in Related Objects > People 2 and made public
5. ORCID id appears on the public page, when clicked, it displays the ORCID Authorizations and synchronization settings page.
6. In the synchronization section of the page, change a setting and then click save, the error should appear. "The update of the synchronization settings failed"

**Expected behavior**
A green confirmation message should be displayed: The update of the synchronization settings succeeded.

**Comment by hutattedonmyarm** [comment] 2024-05-03 13:38
Related: https://github.com/DSpace/DSpace/issues/8925 and #2538

**Comment by tdonohue** [comment] 2024-05-03 14:49
Thanks @hutattedonmyarm for pointing out those relationships.  Now that I look more closely, this ticket seems to be a duplicate of https://github.com/DSpace/DSpace/issues/8925.  The issue described in this ticket is the same as the first bullet in https://github.com/DSpace/DSpace/issues/8925 :

> 1. When users update their ORCID credentials, they always see an error message ("The update of the synchronization settings failed" or "An error occurred while disconnecting between the profile and the ORCID registry. Try again"), regardless of whether the action was successful.

Therefore, I'm going to close this ticket as a duplicate, as there's been more activity on https://github.com/DSpace/DSpace/issues/8925.   I'm still hoping we can find a volunteer to claim that ticket as this is an annoying bug.

**Closed by tdonohue** 2024-05-03 14:49 UTC
Labels: bug, help wanted, testathon, integration: ORCID
