### ISSUE TITLE
radio buttons don't respect type-bind during submission

### ISSUE THREAD

**Issue by hutattedonmyarm** [DSpace/dspace-angular#2687] opened 2023-12-05 12:47 UTC
**Describe the bug**
If type-bind is configured, and a radio button input (`input-type`set to `list` and `repeatable` to `false`) is configured to only appear for specific type-bind values, the radio buttons will ignore this configuration and are always visible

**To Reproduce**
1. Configure type-bind
2. Configure a field with `input-type`set to `list`, `repeatable` to `false` and a specific type-bind value
3. Start a submission
4. The radio buttons will always be visible, no matter if the type-bind matches or not

I'm not sure where to reproduce this on the demo, because I cannot view the submission configuration. However, type-bind is not handled in[ src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list-radio-group.model.ts ](https://github.com/DSpace/dspace-angular/blob/08df2ea1acaa5624539403d152387351a71b8de7/src/app/shared/form/builder/ds-dynamic-form-ui/models/list/dynamic-list-radio-group.model.ts) while it *is* handled in other input models

**Expected behavior**
Radio buttons only appear of the type-bind field matches

**Comment by tdonohue** [comment] 2023-12-05 15:04
I believe this is a possible duplicate of DSpace/DSpace#8678.  Or they are very closely related and may be solved by the same issue.  For now, copying this over to the same 7.6.x board and flagging as "help wanted"

**Comment by hutattedonmyarm** [comment] 2023-12-06 06:09
Yep it's a duplicate of that. I'll work on a fix!

**Closed** 2024-04-30 20:13 UTC
Labels: bug, component: submission, medium priority
