### ISSUE TITLE
Unreliable save when changing order (drag and drop) of multiple entries per MD field in submission form

### ISSUE THREAD

**Issue by Marwa1988-S** [DSpace/dspace-angular#2004] opened 2022-12-16 12:12 UTC
**Describe the bug**
When changing the values order of a metadata field, or adding a new one and then reordering them, sometimes this change is not properly passed in the request, and when testing the newly changed metadata, it was found that the request does not contain the current correct order of metadata values and sometimes not all metadata values themselves if one was deleted after reordering them.

**To Reproduce**
    1. Login
    2. Navigate to the Workflow tasks, claim an item then edit
    3. In edit-submission form add some new keywords
    4. Change the keywords order, then delete one or some of them, then save

**Expected behavior**
The new keywords with their new order should be correct saved but aren't. 

Here is an example:
* There are already these 3 keywords:

![Bildschirmfoto von 2022-12-16 12-12-26](https://user-images.githubusercontent.com/92751337/208094360-51f451f6-e18c-43d6-a8ce-70d18f30a7c8.png)

* Then add new one (kw1), drag it to be the first, and delete the second. then save:
![Bildschirmfoto von 2022-12-16 12-34-13](https://user-images.githubusercontent.com/92751337/208094531-317089ce-f808-41ea-a70d-76a9f979b827.png)

* It is expected that the new keywords are properly saved and displayed, but the result was so in item view page:
![Bildschirmfoto von 2022-12-16 12-34-51](https://user-images.githubusercontent.com/92751337/208094667-4b00c9dd-da1c-41ec-b00f-e537fde39e08.png)

Angular  is firing off an ADD patch and when testing the value in the patch operation where the changed metadata is located, it found that it doesn't always come with the correct metadata.

**Comment by tdonohue** [comment] 2022-12-16 15:58
@Marwa1988-S : Thanks for reporting this.  While your example is showing a custom metadata field (that language-based "Keywords" field doesn't exist by default), I can reproduce this with the default "Author" field for an Item:
1. Submit a normal Item with 3 authors: (Author 1, Author 2, Author 3) to a Collection with workflow enabled
2. As a reviewer, go in and edit that Item. 
3. Add "Author 4".  Drag it to the top of the list.  
4. Remove "Author 1".  
5. The ordering *should now be* "Author 4, Author 2, Author 3".    However, if you save and reload, you'll see the order is "Author 1, Author 3, Author 4".

My best guess here is that the drag and drop reordering of a new value is having some sort of issue.  It appears that "Author 4" is added, but the drag & drop reorder doesn't fully trigger, which means when you remove the second author, you remove "Author 2" instead of "Author 1".

I'll pull this over to our 7.5 board and see if I can find someone to dig into this immediately.

**Comment by tdonohue** [comment] 2023-06-29 20:19
Should be retested in 7.6 to verify problem still exists

**Comment by MW3000** [comment] 2023-08-24 07:42
Yes, I just tested this. The problem is still the same in DSpace 7.6

**Comment by kshepherd** [comment] 2024-07-29 11:52
I have added a longer comment to https://github.com/DSpace/dspace-angular/issues/3217, I believe it is a problem in the subscriptions to valueChanges for onebox components handling fields configured for controlled vocab / authority (even if the values are uncontrolled), and the fact that it does not allow for the group index to change.

**Comment by jlipka** [comment] 2024-08-02 08:11
Due to the many different constellations, I'm not sure whether my approach will help here, but it's worth a try:

Please have a look at this file:
https://github.com/DSpace/DSpace/blob/8bc235b3c9a8bd02bf5eb5506b3d39e9cc43c746/dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/factory/impl/ItemMetadataValueAddPatchOperation.java#L217

Line 217 should AFAIK look like this:
```if (rs.getLeftItem().equals(dso)) {```

This will set the "place" property correctly in the PATCH response and the entries should be displayed correctly in the frontend.

I would appreciate feedback - I may be able to contribute a merge request next week.

Translated with DeepL.com (free version)

**Comment by saschaszott** [comment] 2024-08-02 11:59
> I would appreciate feedback - I may be able to contribute a merge request next week.

@jlipka , this is a valuable finding - I have found more places in the Java code base where the `==` operator is used to compare values (instead of object references). I will create a separate ticket on this. 

At least, the problem described in issue #3217 is **not fixed** by replacing `==` with `equals()` in https://github.com/DSpace/DSpace/blob/8bc235b3c9a8bd02bf5eb5506b3d39e9cc43c746/dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/factory/impl/ItemMetadataValueAddPatchOperation.java#L217

**Comment by saschaszott** [comment] 2024-08-02 12:16
@jlipka , the same line of code can be found in `ItemServiceImpl::moveSingleMetadataValue`.

**Comment by saschaszott** [comment] 2024-08-02 12:27
The invalid usage of the `==` operator in `DSpaceObjectServiceImpl` was fixed a year ago:

https://github.com/DSpace/DSpace/blame/8bc235b3c9a8bd02bf5eb5506b3d39e9cc43c746/dspace-api/src/main/java/org/dspace/content/DSpaceObjectServiceImpl.java#L667

**Comment by kshepherd** [comment] 2024-08-02 14:29
> Line 217 should AFAIK look like this: `if (rs.getLeftItem().equals(dso)) {`
> ...
> I would appreciate feedback - I may be able to contribute a merge request next week.

Hi @jlipka , thanks - yes, this is a good catch and we should definitely be using `.equals()` here. So I think a PR would be very welcome!

This change may solve any issues related to re-ordering/patch update for existing *relationships* displayed in a submission form, but #3217 was specifically about onebox metadata values, as far as I know (typically authority controlled fields), which would not have a relationship and so would not be impacted by this change.

**Comment by saschaszott** [comment] 2024-08-02 15:54
@jlipka I've included the proposed bug fix (line 217 in `ItemMetadataValueAddPatchOperation`) in this PR 👉 https://github.com/DSpace/DSpace/pull/9742

**Comment by pilasou** [comment] 2024-11-22 18:43
HI @jlipka, hi @saschaszott, does the fix added in the already merged PR [#9742](https://github.com/DSpace/DSpace/pull/9742) also fixed the present issue on multiple MD entries ordering?

**Comment by jlipka** [comment] 2024-11-25 09:20
@pilasou I am not able to reproduce the incorrect behavior described above (on demo.dspace.org), so things look good to me.

**Comment by pilasou** [comment] 2024-11-25 14:02
Thanks @jlipka ! @tdonohue given that the incorrect behavior cannot be reproduced (i have also tried on the sandbox both on Subject Keywords and Authors fields: changing order and deleted and then save, the changes are kept), it seems that the PR https://github.com/DSpace/DSpace/pull/9742 has solved this issue and it can be closed.

**Comment by tdonohue** [comment] 2024-12-02 17:01
Closing, appears to have been fixed by https://github.com/DSpace/DSpace/pull/9742 (and was already ported to 7.x for 7.6.3 and 8.x for 8.1)

Thanks for the testing @jlipka and @pilasou !

**Closed by tdonohue** 2024-12-02 17:01 UTC
Labels: bug, help wanted, component: submission, component: workflow, high priority, Estimate TBD
