### ISSUE TITLE
Permanent uri link of Communities, Collections and Items not working

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/dspace-angular#886] opened 2020-10-08 07:30 UTC
**Describe the bug**
On DSpace 7, the permanent URI link of DSpace's items is not working. User is brought to a page with error message "No Item found for the identifier", but item with such identifier should exist
See https://dspace7-demo.atmire.com/handle/10673/1477 or https://dspace7-entities.atmire.com/handle/atmire/444

**To Reproduce**
1. Navigate to an Item / community / collection page 
2. The permanent URI of the item is malformed (opening another issue for this), so the URI has to be copied and the domain has to be replaced with actual one 
3. Paste resulting URI in the browser 

**Expected behavior**
To be brought to a page containing Item related informations

**Comment by abollini** [comment] 2020-10-12 16:48
this is a duplicate of #883

**Closed by abollini** 2020-10-12 16:48 UTC
Labels: bug, needs triage
