### ISSUE TITLE
DESC sort not working in list of sub-communities/sub-collections

### ISSUE THREAD

**Issue by kochm** [DSpace/dspace-angular#2160] opened 2023-03-22 15:53 UTC
In the list of sub-communities on a community page it is not possible to reverse the sort order - it is always ASC by sub-community name - whatever you select in the sort options.

You can see this on the test server at https://demo7.dspace.org/communities/5249eb29-6326-43bb-b5d4-b278a566f7bc - try to change the sort order to DESC, nothing changes.

**Comment by alexandrevryghem** [comment] 2023-04-29 00:29
I would like to claim this issue this is a backend issue this is caused by [this line](https://github.com/DSpace/DSpace/tree/80cb84433b16feab17bb06b0808ed2790551397f/dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/CommunityCollectionLinkRepository.java#L74) (and [this line](https://github.com/DSpace/DSpace/tree/80cb84433b16feab17bb06b0808ed2790551397f/dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/CommunitySubcommunityLinkRepository.java#L70)) because it has been hardcoded in the backend to sort by default using `ASC`

**Comment by tdonohue** [comment] 2023-05-01 14:15
@alexandrevryghem : Sounds good. Assigning to you to work on. Thanks!

**Closed** 2023-05-12 20:00 UTC
Labels: bug, usability, medium priority, component: Community
