### ISSUE TITLE
Flash of unstyled content on DSpace 7 homepage

### ISSUE THREAD

**Issue by alanorth** [DSpace/dspace-angular#1391] opened 2021-11-08 12:34 UTC
**Describe the bug**
I'm not sure if this is "[flash of unstyled content](https://en.wikipedia.org/wiki/Flash_of_unstyled_content)" or not, but when you load the DSpace 7 homepage it seems to load, then flashes white, then shows the content. See this demonstration on dspace7.demo.org in Firefox Nightly:

https://user-images.githubusercontent.com/191754/140742391-5f7576a2-08a0-4293-b71b-2fd43b7ee576.mp4

Is this an issue with _all_ Angular single-page applications or something specific to how we're using Angular? Sorry, I'm not a web developer, but this is surely jarring from a user perspective.

**To Reproduce**
1. Visit https://demo7.dspace.org/

**Expected behavior**
Web page should not flash a white screen during initial loading, even if it takes a few hundred more milliseconds to download the content.

**Comment by alanorth** [comment] 2021-11-08 13:34
Update: for what it's worth, I tried this on a local DSpace 7.1 development instance and the "flash" does not happen. I will close this for now as it must be an issue with the deployment on demo7.dspace.org.

**Comment by tdonohue** [comment] 2021-11-08 15:05
@alanorth : I think this is a duplicate of #1357, and it's something we're investigating / looking into fixing.

**Closed** 2021-11-08 15:08 UTC
Labels: bug, duplicate, improvement, ux

**Comment by alanorth** [comment] 2021-11-08 19:57
Thanks, @tdonohue! I searched for a few different descriptions in existing issues but couldn't find anything. Cheers. :)
