### ISSUE TITLE
Error uploading file

### ISSUE THREAD

**Issue by cuervoest** [DSpace/dspace-angular#1263] opened 2021-07-02 02:27 UTC
While in Submission form drag&drop or browse for a file  get "Upload Failed" on the screen.
In the chrome console i gets an 201 status code message in the post request, with this response body:

errors: [{message: "error.validation.required",…},…]
0: {message: "error.validation.required",…}
1: {message: "error.validation.filerequired", paths: ["/sections/upload"]}
2: {message: "java.io.IOException: No existe el fichero o el directorio", paths: ["/sections/upload"]}
**message: "java.io.IOException: No existe el fichero o el directorio"**
paths: ["/sections/upload"]
id: 30
lastModified: "2021-07-02T02:24:36.051+0000"
sections: {license: {url: null, acceptanceDate: null, granted: false}, upload: {files: []},…}
type: "workspaceitem"
_embedded: {,…}
_links: {,…

I'm using debian with tomcat9 and follows all t he steps during installation. Dspace installation folder gets permisions for tomcat, but not see anything in the dspace logs and not see anything related in catalina logs.

Really try anything befor write this issue

thanks

**Comment by tdonohue** [comment] 2021-07-02 13:39
@cuervoest : this sounds like either a configuration or permissions problem. You'll likely need to turn on debug mode or debug logging in the REST API to get a more detailed error in the response body. See this guide https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

As this isn't a reproducible bug, closing this ticket as "cannot reproduce". If you need further support or have more questions, please use one of our recommended community support options: https://wiki.lyrasis.org/display/DSPACE/Support

**Closed by tdonohue** 2021-07-02 13:39 UTC
Labels: bug, needs triage
