### ISSUE TITLE
Collection template item metadata not used in the submission UI

### ISSUE THREAD

**Issue by artlowel** [DSpace/dspace-angular#748] opened 2020-07-02 09:12 UTC
If you have a collection with an item template, and you start a new submission in that collection. The rest response of the POST to the workspaceItem endpoint will contain the metadata from the item template, so will the linked Item object if you fetch it directly. However the submission UI won't fill those values in the first time the form is rendered.

If you don't fill out anything, but click the "save for later" button, and then edit that submission again the fields do show up.

**Comment by tdonohue** [comment] 2020-10-08 17:39
@atarix83 : It looks like you self-assigned this a while back.  Could you provide an estimate for this work?  Are you still wanting to claim this for beta 5?

**Comment by tdonohue** [comment] 2021-02-24 14:52
@atarix83 : Somehow this ticket got lost between Beta 4 and Beta 5.  Could you estimate this? (It may be dependent on fixing #1034 first)

**Comment by atarix83** [comment] 2021-02-25 09:30
@tdonohue I've verified it again and it seems that the issue is not present anymore. 
On the demo the `1-step Workflow collection` has an item template configured, and if you start a submission there you see the metadata of the template immediately

**Comment by tdonohue** [comment] 2021-02-25 14:50
@atarix83 : Thanks. I'll close this as fixed then.

**Closed by tdonohue** 2021-02-25 14:50 UTC
Labels: Estimate TBD, bug, component: submission

**Comment by yxq477** [comment] 2023-08-18 01:55
unfoturnately,bug still exit.  the `1-step Workflow collection` display is wrong 😂
![new item](https://github.com/DSpace/dspace-angular/assets/13351398/30572b59-2356-4758-b696-3ffd41b878c0)
![collection template](https://github.com/DSpace/dspace-angular/assets/13351398/5e3344be-84fe-4931-a859-9778b8b7e037)


> @tdonohue I've verified it again and it seems that the issue is not present anymore. On the demo the `1-step Workflow collection` has an item template configured, and if you start a submission there you see the metadata of the template immediately

**Comment by tdonohue** [comment] 2023-08-18 15:19
@yxq477 : The screenshots you shared are a misusage of the feature.   You've created a template item which sets the value of `dc.contributor.advisor`, but there is no Advisor field in the submission form.  That is why it's not displaying is because the submission form doesn't have that field.

If you instead create a template item that has `dc.contributor.author` set, you'll see that the value appears in the Authors field.  I've just tried that myself and this feature is working as expected.

If you want to instead create a template item that sets `dc.contributor.advisor`, then you should update your Submission form configuration to display that field.  Then it would also work as expected.

If you have further questions, please use one of our [support channels](https://wiki.lyrasis.org/display/DSPACE/Support).

**Comment by yxq477** [comment] 2023-09-06 02:16
`update your Submission form configuration `

> @yxq477 : The screenshots you shared are an incorrect usage of the feature. You've created a template item which sets the value of `dc.contributor.advisor`, but there is no Advisor field in the submission form. That is why it's not displaying is because the submission form doesn't have that field.
> 
> If you instead create a template item that has `dc.contributor.author` set, you'll see that the value appears in the Authors field. I've just tried that myself and this feature is working as expected.如果您创建一个设置了 `dc.contributor.author` 的模板项，您将看到该值显示在“作者”字段中。我刚刚亲自尝试过，此功能按预期工作。
> 
> If you want to instead create a template item that sets `dc.contributor.advisor`, then you should update your Submission form configuration to display that field. Then it would also work as expected.
> 
> If you have further questions, please use one of our [support channels](https://wiki.lyrasis.org/display/DSPACE/Support).

oh, I understand. thanks for your help
