### ISSUE TITLE
Relationship search window not closing after saving.

### ISSUE THREAD

**Issue by pilasou** [DSpace/dspace-angular#1648] opened 2022-05-11 14:40 UTC
**Describe the bug**
When adding a relation between items (ex: adding a Person relation to a Publication), the search window is not closing after clicking on Save button even if the relation is well created (see print screen below).

![bogue-relation-search](https://user-images.githubusercontent.com/19291880/167876050-819d25f6-8fc3-4e42-b32a-3c7acca1f8cb.png)

**To Reproduce**
1. Connect as admin
2. Edit an item with entity type Publication
3. Clic on the Relations tab.
4. Clic on the green button +Add next to Authors (persons)
5. Select a person in the search window
6. Clic on Save, the window will not close but the relation has been created.

**Expected behavior**
At step 6 above, the search window must close after clicking on Save if the relation is created without errors.

**Related work**
No related works found.

**Comment by tdonohue** [comment] 2022-05-11 15:09
@pilasou : I tried to reproduce this locally and I'm not able to reproduce it in the latest code.  For me, when I click Save (in step 6), I see the relationship created, then the window closes & I get a green success alert in the upper right.

Are you maybe running an older version of the code?  Maybe this was fixed recently already?

You also might want to check to see if there's some sort of error being reported in your browser's DevTools which is blocking the window from closing. See our troubleshooting guide: https://wiki.lyrasis.org/display/DSPACE/Troubleshoot+an+error#Troubleshootanerror-DSpace7.x(orabove)

**Comment by pilasou** [comment] 2022-05-11 17:50
@tdonohue Ok we will look further following your advice. We reproduce this problem on DSpace Demo site: https://demo7.dspace.org/

**Comment by tdonohue** [comment] 2022-05-11 19:04
@pilasou : Please test it again on the demo site at demo7.dspace.org.  I'm not able to reproduce this issue there.  However, it's possible the behavior changed recently as we realized today that the demo site was no longer auto-updating.  So, we pushed out a number of updates today -- it's likely one of those fixed this issue.

**Comment by pilasou** [comment] 2022-05-13 12:36
@tdonohue Thanks, I retry on the demo site. The window do close now but I get an error message: "Erreur lors de l'édition des relations Http failure response for https://api7.dspace.org/server/api/core/relationships?relationshipType=1: 500 500"

**Comment by pilasou** [comment] 2022-08-01 18:09
@tdonohue We have just upgraded to 7.3 and since then, this problem vanished...we are not sure of what caused it though.

**Comment by tdonohue** [comment] 2022-08-01 18:16
@pilasou : thanks for letting me know. As I've been unable to reproduce this, I'm going to close the ticket.  I'm not sure what the cause was either, but glad to see it no longer appears in 7.3.

**Closed by tdonohue** 2022-08-01 18:16 UTC
Labels: bug, cannot reproduce, needs triage
