### ISSUE TITLE
top-level-pagination deeplink does not work properly

### ISSUE THREAD

**Issue by saschaszott** [DSpace/dspace-angular#917] opened 2020-10-25 18:28 UTC
The deeplink

https://dspace7-demo.atmire.com/home?pageId=top-level-pagination&page=25&pageSize=5&sortDirection=ASC&sortField=dc.title

leads to page 25 of the search result list but shows the search hits of page 1 (hits are sorted alphabetically by title).

**To Reproduce**

1. go to https://dspace7-demo.atmire.com/home?pageId=top-level-pagination&page=25&pageSize=5&sortDirection=ASC&sortField=dc.title

**Expected behavior**

Show search hits with rank 121 to 125 (instead of 1 to 5).

**Comment by tdonohue** [comment] 2020-10-26 16:17
This looks to only occur if you go *directly* to that bookmarked link.  I can reproduce it though on the demo site.

In other words, pagination works fine once you load the page.  However, if you bookmark the link, or click "Reload" in your browser, then pagination always starts back over at the first page (even if the URL param says `page=25`, that param seems to be ignored somehow).

This might be a caching or Angular Universal issue...but, it also could be that the URL param is somehow being ignored, and you always start on page 1.

@artlowel : Could someone on your team look at this and estimate?

**Comment by artlowel** [comment] 2020-10-29 13:38
I had a look. While it's related to universal, the root cause of the issue seems to that the pagination params in the url are parsed inside the pagination component: meaning the pagination component must already be rendered before it will check which page it needs to show. 

The top community list component ensures this happens by always fetching the first page first, regardless of the page param in the URL. This will render a pagination component which in turn will check the url and send an update event with the correct page. 

For some reason this update event isn't sent when server side rendering hands over to the client, likely due to things happening in a slightly different order. So the server side version uses the correct page, but gets overwritten with the first page when the client boots up.

I think we should move the code that checks the URL params for pagination options to a service or perhaps to an ngrx effect that puts them in the store, with a service in front can be used to retrieve them. Components using pagination can use that service to get the correct page as soon as they init, and without having to rely on a component being rendered. 

This in itself isn't terribly hard, but there are a lot of components using pagination, and they'll all be affected by the change, and will need to be checked an possibly updated. However since they all either parse the page from the route manually (this is [what the search pages do](https://github.com/DSpace/dspace-angular/blob/main/src/app/core/shared/search/search-configuration.service.ts#L143-L153), and why it isn't a problem there), or have the same problem that may not be a bad thing.

That's why I'd put an estimate of **16h** on this

Since pagination was a contribution from @atarix83, it is perhaps best that he takes a look as well to see if he agrees

**Comment by tdonohue** [comment] 2020-10-29 14:22
@atarix83 : Assigning to you to double check @artlowel's analysis here.  Could you take a look at this when you get a chance?

**Comment by tdonohue** [comment] 2021-01-14 16:03
@artlowel mentioned this in today's meeting as possibly related to #979 (specifically @AndrewZWood 's questions in the PR description about the odd TypeError in his console).  After re-reading @artlowel 's [estimate comment](https://github.com/DSpace/dspace-angular/issues/917#issuecomment-718758213), I agree that these sound like they may be related.  So, I've updated this ticket with the **16 hour** estimate, and kept it scheduled for beta5.

**Closed** 2021-04-06 17:12 UTC
Labels: bug, component: Discovery, e/16, high priority
