### ISSUE TITLE
Upload bitstream bundle lookup is empty 

### ISSUE THREAD

**Issue by aroman-arvo** [DSpace/dspace-angular#2158] opened 2023-03-20 21:32 UTC
**Describe the bug**
Where adding a new file to an item, if teh upload option is selected, the bundle lookup appears empty (but if you click there are values)

**To Reproduce**
Edit an item -> bitstreams -> (top and green) upload -> click bundle
**Expected behavior**
The list should show values
![upload](https://user-images.githubusercontent.com/116575333/226470587-76e4dbc3-96c9-48a5-ad94-5b96144701ec.png)

**Comment by tdonohue** [comment] 2023-03-20 22:10
@aroman-arvo : I believe this is a duplicate of #2101, which was fixed in 7.5 by #2102 

It's possible that fix never got pushed to the demo site though.  So, I'll try and push an update to the demo site shortly.

**Closed by tdonohue** 2023-03-20 22:10 UTC
Labels: bug, needs triage
