### ISSUE TITLE
Adding resource policies with long names fails without a useful error message

### ISSUE THREAD

**Issue by hutattedonmyarm** [DSpace/dspace-angular#1918] opened 2022-10-20 11:57 UTC
**Describe the bug**
When adding a new resource policy, the given name cannot be longer than 30 characters, because the database column holds a `varchar(30)`. Otherwise, creating the policy fails.

However, the input field is not limited to 30 characters, does not provide feedback and no clear error message is shown except a generic "an exception occured". The reason for failing to create the policy has to be dug out of the backend log files

**Expected behavior**
The input field validates its max length, or the server throws a readable error message

**Comment by tdonohue** [comment] 2022-10-20 21:00
Closing this ticket, as I realized it's a duplicate of #1719.  That other ticket is already claimed & hopefully will be fixed in 7.5. See that ticket for more details.

**Closed by tdonohue** 2022-10-20 21:00 UTC
Labels: bug, help wanted, usability, high priority, authorization, good first issue
