### ISSUE TITLE
Adding Relationship to existing Entity sometimes requires multiple clicks

### ISSUE THREAD

**Issue by tdonohue** [DSpace/dspace-angular#1874] opened 2022-09-30 17:49 UTC
**Describe the bug**
On `main`, adding new relationships between Entities is ~~very slow to respond~~ hard to click.  It requires a great amount of patience to get the entity relationship to be created either from the Submission form or the Edit Item form

(UPDATE: It turns out that the issue is NOT a performance problem.  It was that the new thumbnails were overlapping the checkboxes, making it difficult to accurately click on the checkbox.  I assumed it was performance related, but was wrong)

**To Reproduce**
Reproducible in two ways...first from a new submission:
1. Submit a new `Publication` entity
2. In the Author field, click the search icon & attempt to select a "Local Author" already in the system by clicking the checkbox next to their name.
3. Wait for a while.  It might work in ~10 seconds.  It also may require that you click the checkbox a few more times before suddenly the relationship appears in your Submission form.  Here's a screenshot example:
![slow-to-respond-relationships](https://user-images.githubusercontent.com/483997/193327372-8ee08f58-1973-4ecc-b4aa-8d5cbba7a733.png)

Also reproducible when editing an existing Person entity.
1. Browse to a Person entity in the system.
2. Edit the Person, select the "Relationships" tab
3. Attempt to add a new relationship to a Publication.
4. Search for a local "Publication".  Click the checkbox.  It may or may not work immediately.  Once it finally selects though, the relationship may or may not be created (see "Loading..." behind the popup window).  Here's a screenshot example:
![edit-relationships-slow](https://user-images.githubusercontent.com/483997/193327666-e02fa7b1-af6f-42b9-95ab-727570c18610.png)

**Expected behavior**
Obviously a small delay is OK, but there should not be a multiple second delay in creating a relationship.  If there is, there should be some sort of "Creating relationship..." message that appears to let the user know that the relationship is being created.

**Comment by tdonohue** [comment] 2022-09-30 17:52
@artlowel : Not sure if you'd have time to dig into this, but it seems like a big blocker for Entities to work well in 7.4.  Tentatively assigning to you in the hopes you can dig into this next week.

**Comment by artlowel** [comment] 2022-10-03 13:44
@tdonohue I can't reproduce an issue where it takes a long time for a relationship to be added. 
I do see a few other issues regarding relationships though:

1. Due to https://github.com/DSpace/dspace-angular/pull/1780, the padding of the thumbnails almost entirely overlaps the checkboxes or radios used to select a relationship:
<img width="192" alt="image" src="https://user-images.githubusercontent.com/1567693/193588796-ea6433df-e009-4176-97ec-0b638f05bd84.png">
This means that unless you hit the few pixels on the left, you're not actually hitting the checkbox/radio, you're hitting the thumbnail. Perhaps you clicked it a couple of times to get it to work and hit in on the correct side after a while? This can be fixed by adding this to object-list.component.scss:

```sass
ds-selectable-list-item-control {
  z-index: 1
}
```
In any case it should be noted that https://github.com/DSpace/dspace-angular/pull/1329 changed it so a relationship isn't created right when you select something anymore, only on closing the modal.

2. When I add a relationship in the submission, it never seems to show up in the form itself, unless I refresh. This doesn't seem to be an issue with the request to create the relationship, but rather with the form updating to include it afterwards (autosave etc). This is perhaps something @atarix83 could get to the bottom of more quickly

**Comment by tdonohue** [comment] 2022-10-03 14:03
@artlowel : I bet you are correct and I was not always clicking directly on the checkbox.  I suspect that's the issue as I could never pinpoint exactly why sometimes clicking the checkbox would *work* and other times it would remain unchecked.  I probably jumped to the wrong conclusion about it being a performance issue.  Could you submit a small PR to make that SCSS change?  That could be good enough to solve this ticket -- and I can retest to verify that's what what going on for me.

@atarix83 : Any chance you could look into the second issue above? 

> When I add a relationship in the submission, it never seems to show up in the form itself, unless I refresh. This doesn't seem to be an issue with the request to create the relationship, but rather with the form updating to include it afterwards (autosave etc). This is perhaps something @atarix83 could get to the bottom of more quickly

I'm honestly not sure if we'll have time to quickly fix this for 7.4...if not, we can log it as a known bug (in a separate ticket) and get it fixed for 7.5.

**Closed** 2022-10-03 16:22 UTC
Labels: bug, component: submission, component: configurable entities, high priority, performance / caching, component: Item
