### ISSUE TITLE
Login sessions not supported in CSR

### ISSUE THREAD

**Issue by LotteHofstede** [DSpace/dspace-angular#289] opened 2018-09-18 10:15 UTC
When rendering with CSR only, refreshing a page after logging in will log you out (on the client side only, nothing is sent to the server).
However, this does work when SSR is enabled.

The feature was explicitly not implemented for CSR (to prevent performing this action twice, @atarix83 told me):
https://github.com/DSpace/dspace-angular/blob/master/src/app/core/auth/auth.service.ts#L153

This is the implementation for the server side:
https://github.com/DSpace/dspace-angular/blob/master/src/app/core/auth/server-auth.service.ts#L55

Edit: updated line numbers to match the current master

**Comment by tdonohue** [comment] 2020-05-20 19:36
This should be retested now that https://github.com/DSpace/DSpace/pull/2735 has been merged (and deployed to https://dspace7.4science.cloud/server).  It's possible this bug is fixed now that the backend should be returning proper CORS headers.

**Comment by atarix83** [comment] 2020-05-22 15:31
@tdonohue @artlowel 
the issue is not due to CORS, but is an angular bug, I made a PR to solve it

**Comment by tdonohue** [comment] 2020-05-28 15:55
Closing, fixed by #682

**Closed by tdonohue** 2020-05-28 15:55 UTC
Labels: authentication: general, bug
