### ISSUE TITLE
Community/collection title remains when navigating from local to global browse

### ISSUE THREAD

**Issue by emj73** [DSpace/dspace-angular#2425] opened 2023-08-08 20:22 UTC
# Describe bug

When in a community or collection and using the "browse by" function, if you navigate to the global browse feature under "all of dspace" when moving from local "browse by" category (title) to global nav's "all of dspace" browse, same category (title), the community or collection you were in remains. This only happens if you choose the same category. You will be given the all of dspace browse list for the specific category but it displays under the community or collection you were previously viewing. 

reproduce: 
1. Go to DSpace Demo
2. https://demo.dspace.org/community-list 
3. Choose a community that has a couple items like [2023 BIBLIO TIC Villalba](https://demo.dspace.org/communities/1c10270e-49fe-4b16-88aa-2322585896b8)
4. Choose "Browse by Title" and note the number of search results
5. From here, navigate to the global "All of DSpace" menu and choose "By Title"
6. The community/collection title and breadcrumb trail remains, but the search results change

# Expected behavior

if going along with numbers above, in step 5, after clicking a category to browse by, you would be taken to a page that looks like this https://demo.dspace.org/browse/title and does not indicate that you are within a collection or community but rather browsing the entire system.

**Comment by tdonohue** [comment] 2023-09-11 17:04
This does look like a caching bug.  I'm able to reproduce it on the demo site using the instructions above.  Basically in step 5, you have selected to go to the *global* "Browse by Title", and you see those global results.  But, the Community/Collection title/breadcrumbs/logo are still displayed.  It looks like that Community/Collection info is just being cached.

Moving this to the 7.6.x board for investigation by a volunteer.

**Comment by alexandrevryghem** [comment] 2023-12-06 18:21
Atmire would like to claim this issue

**Comment by tdonohue** [comment] 2023-12-06 18:39
Sounds great @alexandrevryghem !  Assigning to you.

**Closed** 2024-02-13 20:22 UTC
Labels: bug, component: Discovery, performance / caching, medium priority

**Comment by tdonohue** [comment] 2024-02-13 20:39
NOTE:  This bug is resolved in 8.0, but it could **not** be ported to 7.6.x.  

The fix required a very large refactor of community/collection pages in #2722 .
