### ISSUE TITLE
In any field where markdown is enabled, any word that ends with a dot and a valid url top level domain will be interpreted as a URL.

### ISSUE THREAD

**Issue by peter975** [DSpace/dspace-angular#3617] opened 2024-11-06 15:17 UTC
## Describe the bug
I'm not sure if this is a bug or a feature request.

In a DSpace 7 & 8 repository where markdown is enabled, a word that ends in a dot followed by a valid web domain will be interpreted as a URL.

## To Reproduce
1. Log in to a DSpace repository with markdown enabled.
2. Find an item and in any field with markdown enabled (default is dc.description.abstract) add words that end in a dot followed by text that matches a web domain (TLD), for example: RUNME.py, ASP.NET
3. They will be rendered as links rather than text

This is not such an edge case as it seems, many publications in fields that use code, for example, will have abstracts that discuss filenames, and where the filename extension matches a url domain they will be rendered as links. Organisations that use dots (periods) in abbrevations of their names will also be affected (eg when Colectivo de Arte Participativo - Tarifa Común is represented as C.A.Pa.Ta.Co) (this last one is how we noticed the behaviour initially).

## Expected behavior
Either:
1. Only valid markdown should be rendered as links, or;
2. DSpace should continue to allow commonmark autolinking (I think this is the cause) but should allow repository managers to disable it in configuration.

## Related work
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment] 2024-11-08 15:08
Closing as a duplicate of #2789.  Please see that ticket instead.

**Closed by tdonohue** 2024-11-08 15:08 UTC
Labels: bug, help wanted, component: Item, affects: main, affects: 8.x, affects: 7.x
