### ISSUE TITLE
Submission dropdowns do not load previously selected and saved value after reload

### ISSUE THREAD

**Issue by toniprieto** [DSpace/dspace-angular#2805] opened 2024-02-13 12:23 UTC
**Describe the bug**
Component `DsDynamicScrollableDropdownComponent` do not load the previously selected value when the component/page is reloaded.

**To Reproduce**
Steps to reproduce the behavior in current demo:
1. Start a new submission
2. Fill in some fields and select a value for the dc.type dropdown field
3. Save the submission
4. Reload the page
5. Other fields are filled, but the dropdown shows an empty value (the value is saved in the item but the component has not loaded the value)

**Expected behavior**
The field should shown the previously selected and saved value after reload

**Related work**
I think this bug has been introduced in this PR #2733 , the component should call to `setCurrentValue(this.model.value, true);` during the initialization but this call has been removed.

Probably adding this call during component initialization can fix the problem:

```
if (this.model.value) {
   this.setCurrentValue(this.model.value, true);
}
```

**Comment by alanorth** [comment] 2024-02-13 14:21
@toniprieto I'm happy you noticed this as well. I can help test if you send a patch, since I was the one who requested and fast tracked the PR that broke this and I was hoping we don't have to revert it before releasing 7.6.2.

**Comment by tdonohue** [comment] 2024-02-13 15:29
@jensvannerum or @artlowel :  Could one of you look into this?  It looks like this is a **new bug** accidentally caused by @jensvannerum 's PR #2733.  If it cannot be fixed, we may need to revert that PR. 

Assigning this to you two in the hopes that one of you (or someone else from Atmire) can take a look.

**Comment by jensvannerum** [comment] 2024-02-14 08:39
Sorry, I've missed this while testing my original PR.

This is on my list now and I will fix it ASAP

**Closed** 2024-02-20 15:38 UTC
Labels: bug, component: submission
