### ISSUE TITLE
Cannot submit to a Collection if given Submitter privileges only

### ISSUE THREAD

**Issue by Aziris** [DSpace/dspace-angular#658] opened 2020-04-27 07:44 UTC
When I add non-admin user to Collection submitters, the user cannot add new Items.

Scenario:
1. create new, non-admin user via CLI command (Peter the Submitter)
2. Log in as admin
3. Create new collection "Collection 1"
4. Open it in Edit mode and in Assign Roles tab press Create button in Submitters section, new group gets created. Cannot be renamed now, but lets call it "Submitters_Group_1"
5. Go to "Access Control/Groups" and edit group "Submitters_Group_1"
6. Find "Peter the Submitter" among EPeople and assign it to "Submitters_Group_1"
7. Log out with admin and log in with "Peter the Submitter"
8. Click to add new Item, select "Collection 1" as parent
9. MyDSpace appears instead of New Item screen with a notification in top-right corner :
"You have not the privilege to make a new submission."
10. For each try to add new Item, MyDSpace gets 1x new dummy entry in it.

![MyDSpace with dummy entries](https://user-images.githubusercontent.com/2697696/80346827-0df58700-8874-11ea-996c-5e66c4dc05fd.JPG)

**Comment by tdonohue** [comment] 2020-05-11 18:31
I'm able to reproduce this bug.  If you login as a someone who has submit permissions in one collection, then you cannot actually submit to that collection successfully.  I've changed the title of this ticket to better describe that.

What occurs is exactly what is described above.  An empty Workspace Item **is created** each time you try to submit to the Collection, however you cannot edit it or see it.  You also always get an error response that says: "You have not the privilege to make a new submission."

**Comment by atarix83** [comment] 2020-10-12 18:52
I can't reproduce the error, @tdonohue can you check if this issue is still valid please?

**Comment by tdonohue** [comment] 2020-10-13 16:56
@atarix83 : You are correct. This appears to be fixed as of 7.0 beta 4, as I cannot reproduce it either.  Closing as fixed.

**Closed by tdonohue** 2020-10-13 16:56 UTC
Labels: Estimate TBD, authorization, bug, component: MyDSpace, component: submission
