### ISSUE TITLE
JWT session lost on browser reload

### ISSUE THREAD

**Issue by Flusspferd123** [DSpace/dspace-angular#428] opened 2019-06-27 06:17 UTC
When  trying to access a protected resource e.g. “…./submit”,  the login page is shown. After log- in there is a redirected to the “…/submit” page. Up to this point everything works as expected. Clicking the reload button at this point results in a loss of the JWT session and the  login page is shown again.

**Comment by artlowel** [comment] 2020-04-29 09:03
Closing, duplicate of #289

**Closed by artlowel** 2020-04-29 09:03 UTC
