### ISSUE TITLE
Login dropdown is blank when only LDAP authentication is enabled

### ISSUE THREAD

**Issue by wwuck** [DSpace/dspace-angular#2701] opened 2023-12-07 02:27 UTC
**Describe the bug**
I am setting up a DSpace 7.6 instance where all users including administrators are coming from LDAP.  I have only `plugin.sequence.org.dspace.authenticate.AuthenticationMethod = org.dspace.authenticate.LDAPAuthentication` set in `local.cfg`. I can do a successful login request on the backend UI web interface, but when I try to login from the frontend angular UI the login dropdown is blank.

![dspace-ui-blank](https://github.com/DSpace/dspace-angular/assets/301402/e98ef6e3-3cfe-4c0c-b302-a90159fc39eb)

If I edit `local.cfg` to also set `plugin.sequence.org.dspace.authenticate.AuthenticationMethod = org.dspace.authenticate.PasswordAuthentication` in addition to the ldap authentication method, then the login dropdown shows a login form.

![dspace-ui-login-form](https://github.com/DSpace/dspace-angular/assets/301402/bafa5161-4c11-449c-839f-67e14d1bb2f5)

Also, when I have only `LDAPAuthentication` method enabled in `local.cfg`, I can execute a successful login via the dspace backend UI and there is only a normal login form there:

![dspace-backend-ui-ldap-login](https://github.com/DSpace/dspace-angular/assets/301402/a3b78423-7467-45b5-8a68-c5abd753e83f)

However when I enable both `LDAPAuthentication` and `PasswordAuthentication`, then I get an extra message appearing on the backend UI login form:

![dspace-backend-ui-ldap-password-login](https://github.com/DSpace/dspace-angular/assets/301402/93d1fe1b-6a89-4c6f-951b-9309d7e486f8)

I couldn't find any documentation on the DSpace wiki on whether `PasswordAuthentcation` method is required to be enabled when using `LDAPAuthentication` method, so I am not sure whether this is either a bug in DSpace or just missing some documentation.

**To Reproduce**
1. Configure and enable `LDAPAuthentication` method in dspace backend `local.cfg`.
2. Navigate to dspace frontend and click "Log in" dropdown at the top of the dspace home page.

**Expected behavior**
When LDAP authentication is enabled in dspace backend according to dspace documenatation, the login form should show correctly on the dspace frontend UI.

**Comment by alexandrevryghem** [comment] 2023-12-07 09:46
@wwuck It's a know bug it's because there is no `@renderAuthMethodFor(AuthMethodType.Ldap)` on the `LogInPasswordComponent`. The problem is that you if you add both `renderAuthMethodFor` decorators to the `LogInPasswordComponent` and enable password & ldap authentication the form displays twice. So in your case you can add it because you don't need to enable both.
Related Issue: https://github.com/DSpace/DSpace/issues/8312

**Comment by alexandrevryghem** [comment] 2023-12-07 13:38
Closing this as it's a duplicate of https://github.com/DSpace/DSpace/issues/8312

**Closed by alexandrevryghem** 2023-12-07 13:38 UTC
Labels: bug, duplicate
