### ISSUE TITLE
Submission Form - incomplete section message when mandatory Author field is populated by Lookup rather than manual entry

### ISSUE THREAD

**Issue by TanyaHolm** [DSpace/dspace-angular#985] opened 2021-01-18 04:14 UTC
I add a new 'Articles' item in demo DSpace.
For mandatory author field I use the 'Lookup' button.
The section shows the "orange" symbol (incomplete section) and I am unable to save the item - but all mandatory fields ARE populated.
However, when I start manually entering an author in the LastName field, the section icon changes to "green" and the item can be saved. When I delete the manually entered author, the form is again "orange".

The form does not recognise that the Author field is populated when using Lookup feature.

**Comment by tdonohue** [comment] 2021-01-21 20:55
Closing, as this is a duplicate of #931.  It's currently being fixed.

**Closed by tdonohue** 2021-01-21 20:55 UTC
