### ISSUE TITLE
Vocabulary element in Sumission form cannot be focused

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1020] opened 2021-02-15 19:21 UTC
Recently (probably after Angular v10 upgrade) vocabulary elements cannot be focused by clicking them.

As example check the "Subject Keywords" in demo site.

![image](https://user-images.githubusercontent.com/2697696/107985801-76644f00-6fd3-11eb-91b0-efc7bf15218e.png)

You can focus the input field only by clicking label of this field (blue area).
Clicking input field directly has no effect.

**Comment by tdonohue** [comment] 2021-02-23 21:02
Can reproduce on https://demo7.dspace.org/, though this appears to be at least partially fixed by https://github.com/DSpace/dspace-angular/pull/1025

**Comment by tdonohue** [comment] 2021-03-02 23:00
@atarix83 : I ran into this same issue while testing #1025 today.  I think this is unrelated to that other issue, but I figured you might be able to estimate this quickly since you are working on other parts of the submission UI.  So, I've assigned this to you for analysis & estimation.  If possible, I'd like to fix this in Beta 5 (since it used to work), but let me know what you find.

**Comment by atarix83** [comment] 2021-03-04 13:23
@tdonohue  I think it could be fixed in 1 hour.

**Closed** 2021-04-02 14:14 UTC
Labels: bug, component: submission, e/1
