### ISSUE TITLE
Forgot password page - Unstable behavior and Submit password button not working

### ISSUE THREAD

**Issue by DSquareTechnologies** [DSpace/dspace-angular#1126] opened 2021-04-25 12:28 UTC
**Describe the bug**
Unable to complete User registration process due to password creation page not loading after clicking password generation link received in email. 

Page supposed to show password fields after clicking on the link disappear immediately after loading and the pre-loader keep running on the page continuously.

After multiple attempts, the page loaded in Incognito mode in Chrome but after entering passwords in both password and re-type password fields, submit button appears de-activated.

**To Reproduce**

1. Go to https://demo7.dspace.org/ and click on Log in link appearing on top right of the page
2. Generate forgot password link by clicking on new user registration and enter your mail id
2. If your mail id is already registered then click on forgot password for generating the link. Enter your mail id and click on save
3. Click on the link received in your email.
4. it will open forgot password page

**Expected behavior**
1. Forgot password page to appear in a stable manner.
2. User should be able to click on Submit password button for saving its password.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment] 2021-04-26 20:53
This appears to be a duplicate of #1113. Closing, as that ticket is already assigned and being worked on.

**Closed by tdonohue** 2021-04-26 20:53 UTC
Labels: authentication: password, bug, duplicate
