### ISSUE TITLE
Cannot use ordinary file browser/selector in Metadata Import (CSV)

### ISSUE THREAD

**Issue by kshepherd** [DSpace/dspace-angular#3219] opened 2024-07-25 13:44 UTC
## Describe the bug
The ordinary file browser / selector to find and upload a CSV file for Import Metadata does not work.  The following console error is shown, and the file is not properly uploaded. This causes the process to start with an empty `-f` parameter and the backend will fail with a relevant error.

I have reproduced this on https://demo.dspace.org, using Brave / Chromium / Firefox browsers.

```
ERROR DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.
    at J.setProperty (https://demo.dspace.org/main.437a6e98e637e96a.js:1:2364003)
    at ra.setProperty (https://demo.dspace.org/main.437a6e98e637e96a.js:1:1279888)
    at Ge.setProperty (https://demo.dspace.org/main.437a6e98e637e96a.js:1:2302901)
    at Ge.writeValue (https://demo.dspace.org/main.437a6e98e637e96a.js:1:2304409)
    at se (https://demo.dspace.org/main.437a6e98e637e96a.js:1:2321720)
    at https://demo.dspace.org/main.437a6e98e637e96a.js:1:2327026
    at Array.forEach (<anonymous>)
    at Cs.setValue (https://demo.dspace.org/main.437a6e98e637e96a.js:1:2327014)
    at https://demo.dspace.org/main.437a6e98e637e96a.js:1:2330852
    at Y.invoke (https://demo.dspace.org/polyfills.278f210b5f97125d.js:1:16949)
```

## To Reproduce
1. Log in as an administrator
2. Click Import -> Metadata in the left-hand admin menu
3. Click 'browse' to use your browser file selection tool to select a valid CSV to upload (you can construct a simple one or export first to get a valid CSV)
4. Note the text in the file area afterwards (no filename), and click proceed. The process will immediately fail, and you will see that the `-f` (filename) parameter has no value
5. Go back to the import page, and this time drag the CSV from a file browser window onto the file area. This time the import should proceed normally.

## Expected behavior
The file selector should work exactly the same as drag and drop.

**Comment by tdonohue** [comment] 2024-07-25 15:37
I'm able to reproduce this on Chrome on Windows as well.

To clarify, everything **works fine** if you drag & drop a file into the upload box.  The error **only occurs** if you click the "browse" link in that upload box and then browse to a file to select it.

This bug appears to be **specific to the Metadata Import** drag & drop box.  I cannot reproduce it in other locations where this same box occurs.

We should retest this when #3189 is fixed, because there might be a slight chance that the two problems are semi-related.  It seems like something on this Metadata Import page is causing links to not work properly.

**Comment by Andrea-Guevara** [comment] 2024-07-30 20:40
Good afternoon @tdonohue!

Unfortunately the resolution of issue #3189 doesn't solve this problem either.

We at Neki-it would like this activity to be assigned to us.

**Comment by tdonohue** [comment] 2024-07-31 21:02
@Andrea-Guevara : Thanks, I've assigned this to you for your team to work on.

**Comment by Andrea-Guevara** [comment] 2024-08-01 16:18
Good afternoon @tdonohue! Here's a PR with a possible solution to this problem:
https://github.com/DSpace/dspace-angular/pull/3230

We look forward to your feedback.

**Closed** 2024-08-03 15:31 UTC
Labels: bug, component: administrative tools, component: file upload, affects: main, affects: 8.x
