### ISSUE TITLE
SSL changues URL for using REST API.

### ISSUE THREAD

**Issue by pgmArvo** [DSpace/dspace-angular#473] opened 2019-09-05 11:39 UTC
In the file \config\enviroment.default.js if you set the value rest.ssl from true to false the connection URL changes from https://host:port/server/api to http://host:port/api. As far as I know, to work it should be http://host:port/server/api.
Is this a bug or funcionality I'm not understanding right?

**Comment by tdonohue** [comment] 2019-09-06 15:33
@pgmArvo : That sounds like a bug to me, as both should use the `nameSpace` setting to determine the URL.  

However, that's also very odd behavior to me, as I'm not able to reproduce this locally.  For example, I'm able to use the below configuration to point the Angular UI at my REST API running locally on "http://localhost:8080/server/api":
```
rest: {
    ssl: false,
    host: 'localhost',
    port: 8080,
    // NOTE: Space is capitalized because 'namespace' is a reserved string in TypeScript
    nameSpace: '/server/api'
  },
```

Could you double check that you don't have other `environment.*.js` files that are being loaded to change this behavior?   For example, if you are running in "Development" mode, then an `environment.dev.js` file would override any settings in `environment.default.js`.

**Comment by pgmArvo** [comment] 2019-09-10 10:23
Not sure what happened.
I was taking screenshots to prove the bug and I wasn't able to reproduce. I did some pulls after noticing the bug so maybe they fixed it, not sure.
Sorry for losing your time, closing.

**Comment by pgmArvo** [comment] 2019-09-10 10:41
I probably did something wrong. Still, just in case, I will show how I could reproduce the bug.
First let's take as starting point the default configuration:
![2019-09-10](https://user-images.githubusercontent.com/48796511/64606787-5c2e4680-d3c7-11e9-97ca-ed9eb5899f04.png)
An test it with a login petition.
![2019-09-10 (1)](https://user-images.githubusercontent.com/48796511/64606941-baf3c000-d3c7-11e9-947e-5985bb9861c9.png)
The URL of the petition is the expected one.
Then, let's modify the URL by changuing the host and the port:
![2019-09-10 (4)](https://user-images.githubusercontent.com/48796511/64606995-dced4280-d3c7-11e9-9b21-e6c137986193.png)
And test it again with a login petition.
![imagen](https://user-images.githubusercontent.com/48796511/64607079-09a15a00-d3c8-11e9-8f5b-c6aa83931e40.png)
Again, the URL of the petition is the expected one.
Finally, let's modify again the URL by chaguing the ssl to false:
![2019-09-10 (2)](https://user-images.githubusercontent.com/48796511/64607121-26d62880-d3c8-11e9-9d99-b3cd26607fcc.png)
And test it again with a login petition.
![2019-09-10 (3)](https://user-images.githubusercontent.com/48796511/64607137-3190bd80-d3c8-11e9-9fa0-01e00191fbdb.png)
In this case the URL isn't the expected one, as it is lacking "/server" before "/api".

**Comment by pgmArvo** [comment] 2019-09-10 10:43
I guess I'm not having problems with the environment.default.js file as if it was override by other file it's changues wouldn't apply at all.

**Comment by tdonohue** [comment] 2022-12-06 15:36
Closing as outdate/obsolete as `environment.*.js` no longer exists.

**Closed by tdonohue** 2022-12-06 15:36 UTC
Labels: configuration
