### ISSUE TITLE
Lazy routing "hide" parse errors

### ISSUE THREAD

**Issue by atarix83** [DSpace/dspace-angular#177] opened 2017-10-06 08:52 UTC
Hi, 
with Lazy routing, whether the route has a parse error, it can't be seen because the error provided is always the same: 
`TypeError: Cannot assign to read only property 'microTask' of object '[object Object]'`

For instance I was blocked by this error in my page 
`Error: Template parse errors: There is no directive with "exportAs" set to "testForm1" ` 
but I found it only when I move my route out of the lazy loading.

It can be useful if we find a way to disable lazy routing during development.

**Comment by artlowel** [comment] 2017-10-06 08:55
Disable it during development, or just have a way of seeing the cause of the error

**Comment by artlowel** [comment] 2017-10-11 07:32
I found that [enabling tracing on the router](https://dzone.com/articles/note-to-self-debugging-angular-4-routing) was one way to get to know the actual error, but perhaps this won't work in all cases.

**Comment by tdonohue** [comment] 2020-04-29 20:51
This seems to be an answered question (not a bug report). Closing

**Closed by tdonohue** 2020-04-29 20:51 UTC
Labels: ready
