### ISSUE TITLE
Export matadata in other bibliographic formats besides .csv (.ris, .enl, .bib)

### ISSUE THREAD

**Issue by rsaraivac** [DSpace/dspace-angular#3204] opened 2024-07-18 11:28 UTC
## Describe the solution you'd like
Possibility of exporting publications metadata (invididually and in bulk) in other bibliographic formats (.ris, .enl, .bib) besides .csv

**Comment by mwoodiupui** [comment] 2024-07-19 12:10
Related to #8234?

**Comment by tdonohue** [comment] 2024-07-19 17:12
@mwoodiupui : Good catch!  I forgot about that other ticket. I think you are correct, that this might be a duplicate of https://github.com/DSpace/DSpace/issues/8234   In fact, since that other ticket has a lot more activity, I'll close this one as a duplicate.

Closing as a duplicate of https://github.com/DSpace/DSpace/issues/8234   See that ticket for further details.

**Closed by tdonohue** 2024-07-19 17:12 UTC
Labels: help wanted, new feature, tools: export
