### ISSUE TITLE
Implement the group edit 

### ISSUE THREAD

**Issue by abollini** [DSpace/dspace-angular#836] opened 2020-08-14 07:56 UTC
In https://github.com/DSpace/dspace-angular/pull/613 the edit of group was left out but the feature is now completely supported by the backend.

We are working on it, the group service will be extended to send the patch request for both the name than the dc.description metadata. The result will be shown in a message to the user, if the operation succeed the user is redirect to the group list page.

**Comment by tdonohue** [comment] 2020-10-28 14:27
As noted in Slack, this is an accidental duplicate of #911 .

**Comment by tdonohue** [comment] 2020-10-30 14:43
Closing as a duplicate of #911.  See #911 for the PR which will fix this issue.

**Closed by tdonohue** 2020-10-30 14:43 UTC
Labels: component: administrative tools, e/2
