### ISSUE TITLE
Licence accept prompt not translatable 

### ISSUE THREAD

**Issue by MarisArins** [DSpace/dspace-angular#1335] opened 2021-09-26 18:49 UTC
1. Change UI language to anything but EN
2. Open Submission form 
3. check the license segment at bottom of form
4. there are still english text visible "I confirm the license above"

There is no way to properly translate "I confirm the license above" checkbox prompt and related error message "You must accept the license" depending on selected language, as these are "generated" from static JSON

**Comment by tdonohue** [comment] 2021-09-27 15:22
Confirmed, the text is currently hardcoded in https://github.com/DSpace/dspace-angular/blob/main/src/app/submission/sections/license/section-license.model.ts

It appears to me that this JSON is being passed to the [ng-dynamic-forms library](https://github.com/udos86/ng-dynamic-forms#json-form-models), which doesn't appear (unless I'm missing it) to support i18n keys in the JSON.  So, fixing this bug may require refactoring slightly how that `section-license.component.ts` works so that it can better support i18n.

**Comment by toniprieto** [comment] 2022-07-28 07:06
@tdonohue This issue can be closed. It is a duplicate of the recently closed issue #1487

**Comment by tdonohue** [comment] 2022-07-28 13:55
Closing as duplicate of #1487 .  This was fixed in 7.4 by #1708

**Closed by tdonohue** 2022-07-28 13:55 UTC
Labels: bug, help wanted, i18n / l10n, component: submission
