### ISSUE TITLE
Delete button in Workflow not working!

### ISSUE THREAD

**Issue by unibravo** [DSpace/dspace-angular#2134] opened 2023-03-06 06:58 UTC
**Describe the bug**
Delete button in Workflow not working!

Note: Our client migrating to 7.5 has the same problem!
Note: Delete button worked in 7.4 Angular!

Example workflow items deleting links:
https://demo7.dspace.org/workflowitems/191/delete
https://demo7.dspace.org/workflowitems/192/delete

**To Reproduce**
1. Go Administer Workflow menu (Angular)
2. Select a workflow item you want to delete
3. Click Delete button

**Expected behavior**
When the delete button is clicked, it should perform the deletion process.

**Related work**
Link to any related tickets or PRs here.

**Comment by tdonohue** [comment] 2023-03-06 15:51
This is a duplicate of #2118 .  @atarix83 and his team will be working on a fix...it appears these buttons somehow broke in the 7.5 release. See that ticket for more info.

**Closed by tdonohue** 2023-03-06 15:51 UTC
Labels: bug, duplicate
