### ISSUE TITLE
When creating a new EPerson "Reset password" button is not needed

### ISSUE THREAD

**Issue by corrad82-4s** [DSpace/dspace-angular#2026] opened 2023-01-05 08:07 UTC
**Describe the bug**
This isn't properly a bug, but a behavior that might confuse administrators when creating a new EPerson. 
Current EPerson form does not make distinctions between the creation of a new EPerson and the edit of an existing one. In particular the set of buttons is the same. 

**To Reproduce**
1. login as administrator
2. Go to "Access Control / People"
3. Click "Add Person"
4. The form will propose "Reset password" button

**Expected behavior**
In our opinion, it could be a good improvement if, when a new person is created: 
- "Reset password" button is not displayed
- Instead of "Save" the "Create" label is displayed on the button that creates the EPerson
- (Nice to have) when "Save / Create" button is clicked (only in case of new EPerson) the user registration mail is automatically sent

We, at 4Science, are interested in working on this improvement for which we roughly estimate from 1 to 2 days of work

**Comment by amanbudgujar** [comment] 2023-02-28 07:45
@tdonohue 
Please assign this to me. I can work on this.
Estimated time - 2 days

**Comment by amanbudgujar** [comment] 2023-03-01 07:17
@tdonohue @corrad82-4s 
I have a query regarding the 3rd point in the **Expected Behaviour** part in the description above.
> (Nice to have) when "Save / Create" button is clicked (only in case of new EPerson) the user registration mail is automatically sent

What's a purpose of sending a user registration mail when there is going to be no password for the user to login?
Shouldn't we send a forgot password link instead so that the user can generate his/her password on it own?

**Comment by tdonohue** [comment] 2023-03-01 15:45
@amanbudgujar :  I think your understanding is correct. 

First, because it's listed as "Nice to have", that feature is NOT required to close this ticket.  It's optional.

But, if you choose to implement it, then I'd agree that it should trigger a forgot password / reset password email.

So, essentially, the "Reset Password" button should be removed, but clicking "Save" on a *NEW* EPerson should trigger the same action that the "Reset Password" button triggers for an *existing* EPerson.

**Comment by amanbudgujar** [comment] 2023-03-03 07:08
@tdonohue 
Can you get PR #2130 reviewed?
And about the 3rd point point in the description,
> (Nice to have) when "Save / Create" button is clicked (only in case of new EPerson) the user registration mail is automatically sent.

I have done this but it's on the backend. I tried it on the front end but the existing function made for sending a password reset link seems to be working only when the edit mode is on. 
You can generate a ticket in the backend regarding this issue, I'll be happy to send a PR over there.
Thanks.

**Closed** 2023-03-23 19:38 UTC
Labels: bug, usability, authorization, component: administrative tools, medium priority
