### ISSUE TITLE
pagination in recent submissions page does not work properly

### ISSUE THREAD

**Issue by saschaszott** [DSpace/dspace-angular#919] opened 2020-10-25 22:31 UTC
**Describe the bug**

https://dspace7-demo.atmire.com/collections/9398affe-a977-4992-9a1d-6f00908a259f?pageId=collection-page-pagination&page=1&pageSize=5&sortDirection=DESC&sortField=dc.date.accessioned

shows 4 instead of 5 entries.

Furthermore, switching to page 2 and 3 of the search list shows the same (4) entries.

**To Reproduce**
1. open https://dspace7-demo.atmire.com/collections/9398affe-a977-4992-9a1d-6f00908a259f?pageId=collection-page-pagination&page=1&pageSize=5&sortDirection=DESC&sortField=dc.date.accessioned
2. go to page 2 or 3

**Expected behavior**

Page 1 and 2 should contain 5 (different) entries (instead of 4). Page 3 consists of exactly one entry.

**Comment by tdonohue** [comment] 2020-10-26 16:02
Closing, as this is a duplicate of #680 (which is already scheduled for beta 5)

**Closed by tdonohue** 2020-10-26 16:02 UTC
Labels: bug, needs triage
