### ISSUE TITLE
File download problem in the item submission phase

### ISSUE THREAD

**Issue by kanasznagyzoltan** [DSpace/dspace-angular#1644] opened 2022-05-09 11:33 UTC
Using DSpace 7.2,  the user is creating a new item via the item submission form and upload a file, the file is not downloadable (and could not be checked by the user) until the item is published.

1. Login to the DSpace 7.2 (angular) UI
2. Visit MyDSpace page
3. Start a new submission into any collection the actually logged in user has permission
4. Upload a file
5. Download the previously uploaded file
6. using the dowload icon ![image](https://user-images.githubusercontent.com/32355628/167401419-f69692e3-0284-42f7-8b70-722c65a79382.png)  ![image](https://user-images.githubusercontent.com/32355628/167400128-b87cf530-0800-4d97-a267-4fe94c857b08.png)

8. but this has given me the following error page
![image](https://user-images.githubusercontent.com/32355628/167400908-18cab7a4-bc57-4ce4-ac1f-49882cb8e26a.png)

**Expected behavior**
The user can download the previously uploaded file and can verify his/her upload was correct.

**Comment by kanasznagyzoltan** [comment] 2022-05-09 11:34
Could somebody help me if this bugfix could be in the 7.3 release?

**Comment by kanasznagyzoltan** [comment] 2022-05-10 09:10
Thanks @tdonohue

**Comment by kanasznagyzoltan** [comment] 2022-05-10 09:13
You mentioned the demo site, I tested this bug yesterday on this site: https://demo7.dspace.org/home
If it is the same site the one you mentioned the problem still occurs.

**Comment by tdonohue** [comment] 2022-05-20 21:48
Still unable to reproduce this locally, though it can be reproduced at demo7.dspace.org.  It's *possible* this is a misconfiguration of the demo site, unless someone else is able to reproduce this in another location.

**Comment by pilasou** [comment] 2022-08-17 19:22
This is the same problem we reported last june: https://github.com/DSpace/DSpace/issues/8378 We found a workaround (see issues comments), but no long term solution.

**Comment by tdonohue** [comment] 2022-08-23 16:27
Closing as a duplicate of https://github.com/DSpace/DSpace/issues/8378.  This issue still exists however, and I think @pilasou is correct that this is a bug in the codebase.  Please see that ticket for more details (including the [only known workaround so far](https://github.com/DSpace/DSpace/issues/8378#issuecomment-1169197172))

**Closed by tdonohue** 2022-08-23 16:27 UTC
Labels: bug, high priority
