### ISSUE TITLE
Workflow collection cannot be updated

### ISSUE THREAD

**Issue by CrisGuzmanS** [DSpace/dspace-angular#2140] opened 2023-03-09 16:28 UTC
**Describe the bug**
When the user edit a Workflow item and tries to update a collection an error appears.

**To Reproduce**
1. Login
2. Go to workflow items list section
3. Edit any workflow item
4. Try to change the collection.
5. You will recive an error 500 in the console:
![image](https://user-images.githubusercontent.com/51240376/224088230-920d8531-92bb-4483-95fc-a86fb5b09de3.png)

These are the general header:
![image](https://user-images.githubusercontent.com/51240376/224089497-8f27d817-a360-4273-9445-c6b887443f85.png)

These are the parameters that was sent:
![image](https://user-images.githubusercontent.com/51240376/224089674-d3562ab4-e2d3-49a2-913d-4fd5b96615b7.png)

**Expected behavior**
User should be able to modify the collection for the workflow item

**Comment by tdonohue** [comment] 2023-03-09 16:35
This is a known issue... it was also reported on the backend here: https://github.com/DSpace/DSpace/issues/7965

The general consensus is that this feature likely **needs to be disabled**.  It's not easy to move an Item between Collections once it has entered a Workflow.  Every Collection can have a different Workflow, and if you were to move an Item to a new Collection, you'd have to completely cancel the current Workflow and start a new Workflow (based on the new Collection). 

See discussion on that other ticket.

If anyone is interested in simply disabling this feature (so that the Collection cannot be changed at all), that might be a good "quick fix"

**Comment by CrisGuzmanS** [comment] 2023-03-09 19:30
That is True this feature is not trivial. So i think this issue can be closed. Maybe i can work on https://github.com/DSpace/DSpace/issues/7965 i will let you know in that issue if i can be assigned to that.

**Comment by tdonohue** [comment] 2023-03-09 19:36
Closing as a duplicate of https://github.com/DSpace/DSpace/issues/7965

**Closed by tdonohue** 2023-03-09 19:36 UTC
Labels: bug, duplicate, component: submission, component: workflow
